2023-03-16 10:40:06 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 10:40:15 [ERROR] util.logger generate_otp_api.py:23: Failed to push OTP Invalid Mobile Number
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\authenticate\generate_otp_api.py", line 15, in index
    mobile_number = validate_and_format_mobile_number(request.data.get("mobile_number", None))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\aravind\lens35\util\regex.py", line 9, in validate_and_format_mobile_number
    raise Exception("Invalid Mobile Number")
Exception: Invalid Mobile Number

2023-03-16 10:40:15 [WARNING] django.request log.py:241: Bad Request: /employees/apis/generate/otp/
2023-03-16 10:40:44 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\apis\authenticate\generate_otp_api.py changed, reloading.
2023-03-16 10:40:45 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 10:40:59 [WARNING] django.request log.py:241: Too Many Requests: /employees/apis/generate/otp/
2023-03-16 10:41:06 [ERROR] util.logger generate_token_api.py:47: Failed : Invalid OTP
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\authenticate\generate_token_api.py", line 21, in index
    otp = validate_and_format_otp(data.get("otp", None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\aravind\lens35\util\regex.py", line 18, in validate_and_format_otp
    raise Exception("Invalid OTP")
Exception: Invalid OTP

2023-03-16 10:41:06 [WARNING] django.request log.py:241: Bad Request: /employees/apis/generate/token/
2023-03-16 10:44:18 [WARNING] django.request log.py:241: Too Many Requests: /employees/apis/generate/otp/
2023-03-16 10:44:29 [DEBUG] util.logger generate_token_api.py:81: Creating new Employee record
2023-03-16 12:33:38 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 12:34:33 [WARNING] django.request log.py:241: Unauthorized: /employees/apis/generate/token/
2023-03-16 12:40:06 [DEBUG] util.logger authenticate.py:55: employees authorization info : f563ede1-e736-4b8f-9a0b-ddd03935aae5 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : 3e7beed7-bbe1-4cce-aa5f-48d1b46b492b
2023-03-16 12:40:06 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 12:40:06 [WARNING] django.request log.py:241: Not Found: /employees/apis/profile/update/services/
2023-03-16 12:41:16 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\api_urls.py changed, reloading.
2023-03-16 12:41:16 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 12:41:43 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\api_urls.py changed, reloading.
2023-03-16 12:41:44 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 12:41:50 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\api_urls.py changed, reloading.
2023-03-16 12:41:51 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 12:41:53 [DEBUG] util.logger authenticate.py:55: employees authorization info : f563ede1-e736-4b8f-9a0b-ddd03935aae5 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : 3e7beed7-bbe1-4cce-aa5f-48d1b46b492b
2023-03-16 12:41:53 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 12:45:03 [DEBUG] util.logger authenticate.py:55: employees authorization info : f563ede1-e736-4b8f-9a0b-ddd03935aae5 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : 3e7beed7-bbe1-4cce-aa5f-48d1b46b492b
2023-03-16 12:45:03 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 12:45:03 [DEBUG] util.logger authenticate.py:55: employees authorization info : f563ede1-e736-4b8f-9a0b-ddd03935aae5 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : 3e7beed7-bbe1-4cce-aa5f-48d1b46b492b
2023-03-16 12:45:03 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 12:45:04 [DEBUG] util.logger authenticate.py:55: employees authorization info : f563ede1-e736-4b8f-9a0b-ddd03935aae5 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : 3e7beed7-bbe1-4cce-aa5f-48d1b46b492b
2023-03-16 12:45:05 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 12:45:06 [DEBUG] util.logger authenticate.py:55: employees authorization info : f563ede1-e736-4b8f-9a0b-ddd03935aae5 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : 3e7beed7-bbe1-4cce-aa5f-48d1b46b492b
2023-03-16 12:45:06 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 12:45:11 [DEBUG] util.logger authenticate.py:55: employees authorization info : f563ede1-e736-4b8f-9a0b-ddd03935aae5 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : 3e7beed7-bbe1-4cce-aa5f-48d1b46b492b
2023-03-16 12:45:11 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 12:45:14 [DEBUG] util.logger authenticate.py:55: employees authorization info : f563ede1-e736-4b8f-9a0b-ddd03935aae5 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : 3e7beed7-bbe1-4cce-aa5f-48d1b46b492b
2023-03-16 12:45:14 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 12:45:15 [DEBUG] util.logger authenticate.py:55: employees authorization info : f563ede1-e736-4b8f-9a0b-ddd03935aae5 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : 3e7beed7-bbe1-4cce-aa5f-48d1b46b492b
2023-03-16 12:45:15 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 12:45:20 [DEBUG] util.logger authenticate.py:55: employees authorization info : f563ede1-e736-4b8f-9a0b-ddd03935aae5 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : 3e7beed7-bbe1-4cce-aa5f-48d1b46b492b
2023-03-16 12:45:20 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 12:45:33 [DEBUG] util.logger authenticate.py:55: employees authorization info : f563ede1-e736-4b8f-9a0b-ddd03935aae5 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : 3e7beed7-bbe1-4cce-aa5f-48d1b46b492b
2023-03-16 12:45:33 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 12:45:39 [DEBUG] util.logger authenticate.py:55: employees authorization info : f563ede1-e736-4b8f-9a0b-ddd03935aae5 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : 3e7beed7-bbe1-4cce-aa5f-48d1b46b492b
2023-03-16 12:45:39 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 12:45:39 [ERROR] util.logger basic_info.py:71: Failed to update employee basic info c577aff1-b951-404d-84a9-8739a4c43917 - profile name must not contain symbols or spaces
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\profile\update\basic_info.py", line 35, in index
    raise Exception("profile name must not contain symbols or spaces")
Exception: profile name must not contain symbols or spaces

2023-03-16 12:45:39 [WARNING] django.request log.py:241: Bad Request: /employees/apis/profile/update/basic
2023-03-16 12:45:45 [DEBUG] util.logger authenticate.py:55: employees authorization info : f563ede1-e736-4b8f-9a0b-ddd03935aae5 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : 3e7beed7-bbe1-4cce-aa5f-48d1b46b492b
2023-03-16 12:45:46 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 12:45:47 [DEBUG] util.logger authenticate.py:55: employees authorization info : f563ede1-e736-4b8f-9a0b-ddd03935aae5 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : 3e7beed7-bbe1-4cce-aa5f-48d1b46b492b
2023-03-16 12:45:47 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 12:45:52 [DEBUG] util.logger authenticate.py:55: employees authorization info : f563ede1-e736-4b8f-9a0b-ddd03935aae5 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : 3e7beed7-bbe1-4cce-aa5f-48d1b46b492b
2023-03-16 12:45:52 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 12:45:52 [ERROR] util.logger basic_info.py:71: Failed to update employee basic info c577aff1-b951-404d-84a9-8739a4c43917 - Imvalid Email ID
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\profile\update\basic_info.py", line 42, in index
    email_id = validate_and_format_email_id(email_id)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\aravind\lens35\util\regex.py", line 54, in validate_and_format_email_id
    raise Exception("Imvalid Email ID")
Exception: Imvalid Email ID

2023-03-16 12:45:52 [WARNING] django.request log.py:241: Bad Request: /employees/apis/profile/update/basic
2023-03-16 12:45:55 [DEBUG] util.logger authenticate.py:55: employees authorization info : f563ede1-e736-4b8f-9a0b-ddd03935aae5 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : 3e7beed7-bbe1-4cce-aa5f-48d1b46b492b
2023-03-16 12:45:55 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 12:45:58 [DEBUG] util.logger authenticate.py:55: employees authorization info : f563ede1-e736-4b8f-9a0b-ddd03935aae5 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : 3e7beed7-bbe1-4cce-aa5f-48d1b46b492b
2023-03-16 12:45:58 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 12:45:58 [ERROR] util.logger basic_info.py:71: Failed to update employee basic info c577aff1-b951-404d-84a9-8739a4c43917 - JSON parse error - Expecting value: line 6 column 1 (char 162)
Traceback (most recent call last):
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\parsers.py", line 64, in parse
    return json.load(decoded_stream, parse_constant=parse_constant)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\utils\json.py", line 31, in load
    return json.load(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 6 column 1 (char 162)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\profile\update\basic_info.py", line 14, in index
    data = request.data
           ^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\request.py", line 216, in data
    self._load_data_and_files()
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\request.py", line 279, in _load_data_and_files
    self._data, self._files = self._parse()
                              ^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\request.py", line 354, in _parse
    parsed = parser.parse(stream, media_type, self.parser_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\parsers.py", line 66, in parse
    raise ParseError('JSON parse error - %s' % str(exc))
rest_framework.exceptions.ParseError: JSON parse error - Expecting value: line 6 column 1 (char 162)

2023-03-16 12:45:58 [WARNING] django.request log.py:241: Bad Request: /employees/apis/profile/update/basic
2023-03-16 12:46:03 [DEBUG] util.logger authenticate.py:55: employees authorization info : f563ede1-e736-4b8f-9a0b-ddd03935aae5 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : 3e7beed7-bbe1-4cce-aa5f-48d1b46b492b
2023-03-16 12:46:04 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 12:46:41 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\apis\profile\update\basic_info.py changed, reloading.
2023-03-16 12:46:41 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 12:46:46 [DEBUG] util.logger authenticate.py:55: employees authorization info : f563ede1-e736-4b8f-9a0b-ddd03935aae5 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : 3e7beed7-bbe1-4cce-aa5f-48d1b46b492b
2023-03-16 12:46:46 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 12:46:54 [DEBUG] util.logger authenticate.py:55: employees authorization info : f563ede1-e736-4b8f-9a0b-ddd03935aae5 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : 3e7beed7-bbe1-4cce-aa5f-48d1b46b492b
2023-03-16 12:46:54 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 12:46:56 [DEBUG] util.logger authenticate.py:55: employees authorization info : f563ede1-e736-4b8f-9a0b-ddd03935aae5 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : 3e7beed7-bbe1-4cce-aa5f-48d1b46b492b
2023-03-16 12:46:56 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 12:47:01 [DEBUG] util.logger authenticate.py:55: employees authorization info : f563ede1-e736-4b8f-9a0b-ddd03935aae5 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : 3e7beed7-bbe1-4cce-aa5f-48d1b46b492b
2023-03-16 12:47:01 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 12:49:30 [ERROR] util.logger generate_token_api.py:47: Failed : expected string or bytes-like object, got 'int'
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\authenticate\generate_token_api.py", line 21, in index
    otp = validate_and_format_otp(data.get("otp", None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\aravind\lens35\util\regex.py", line 15, in validate_and_format_otp
    if(re.findall("^[2-9]{1}[0-9]{5}$", otp)):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\re\__init__.py", line 216, in findall
    return _compile(pattern, flags).findall(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'int'

2023-03-16 12:49:30 [WARNING] django.request log.py:241: Bad Request: /employees/apis/generate/token/
2023-03-16 12:49:46 [DEBUG] util.logger authenticate.py:55: employees authorization info : cdd986e1-350a-451f-8f1d-f65b1ac620b9 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : d648885a-a67b-4cfa-b6c7-5809b07d13f5
2023-03-16 12:49:46 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 12:54:12 [ERROR] util.logger generate_token_api.py:47: Failed : Device id must be a valid UUID4 (or null)
Traceback (most recent call last):
  File "C:\aravind\lens35\util\regex.py", line 28, in validate_and_format_uuid4
    return UUID(uuid_value, version=4)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\uuid.py", line 178, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\authenticate\generate_token_api.py", line 33, in index
    device_id = validate_and_format_uuid4("device_id", data.get("device_id", None), True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\aravind\lens35\util\regex.py", line 30, in validate_and_format_uuid4
    raise Exception("Device id must be a valid UUID4 (or null)")
Exception: Device id must be a valid UUID4 (or null)

2023-03-16 12:54:12 [WARNING] django.request log.py:241: Bad Request: /employees/apis/generate/token/
2023-03-16 12:55:25 [WARNING] django.request log.py:241: Unauthorized: /employees/apis/generate/token/
2023-03-16 12:55:43 [DEBUG] util.logger authenticate.py:55: employees authorization info : 98ae2685-f0d1-4162-9318-b095b61695c0 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 12:55:43 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 12:57:49 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\api_urls.py changed, reloading.
2023-03-16 12:57:49 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 12:57:54 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\api_urls.py changed, reloading.
2023-03-16 12:57:54 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 12:58:00 [DEBUG] util.logger authenticate.py:55: employees authorization info : 98ae2685-f0d1-4162-9318-b095b61695c0 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 12:58:00 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 12:58:00 [WARNING] django.request log.py:241: Not Found: /employees/apis/profile/update/services/
2023-03-16 12:58:21 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\api_urls.py changed, reloading.
2023-03-16 12:58:21 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 12:58:24 [DEBUG] util.logger authenticate.py:55: employees authorization info : 98ae2685-f0d1-4162-9318-b095b61695c0 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 12:58:24 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 12:58:24 [WARNING] django.request log.py:241: Not Found: /employees/apis/profile/update/services/
2023-03-16 12:58:39 [DEBUG] util.logger authenticate.py:55: employees authorization info : 98ae2685-f0d1-4162-9318-b095b61695c0 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 12:58:39 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 12:58:50 [DEBUG] util.logger authenticate.py:55: employees authorization info : 98ae2685-f0d1-4162-9318-b095b61695c0 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 12:58:51 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 12:59:59 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\apis\profile\update\services.py changed, reloading.
2023-03-16 12:59:59 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 13:00:01 [DEBUG] util.logger authenticate.py:55: employees authorization info : 98ae2685-f0d1-4162-9318-b095b61695c0 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:00:01 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 13:00:08 [DEBUG] util.logger authenticate.py:55: employees authorization info : 98ae2685-f0d1-4162-9318-b095b61695c0 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:00:08 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 13:00:10 [DEBUG] util.logger authenticate.py:55: employees authorization info : 98ae2685-f0d1-4162-9318-b095b61695c0 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:00:10 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 13:00:11 [DEBUG] util.logger authenticate.py:55: employees authorization info : 98ae2685-f0d1-4162-9318-b095b61695c0 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:00:11 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 13:06:34 [DEBUG] util.logger authenticate.py:55: employees authorization info : 98ae2685-f0d1-4162-9318-b095b61695c0 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:06:34 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 13:06:40 [DEBUG] util.logger authenticate.py:55: employees authorization info : 98ae2685-f0d1-4162-9318-b095b61695c0 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:06:40 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 13:06:48 [DEBUG] util.logger authenticate.py:55: employees authorization info : 98ae2685-f0d1-4162-9318-b095b61695c0 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:06:48 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 13:06:58 [DEBUG] util.logger authenticate.py:55: employees authorization info : 98ae2685-f0d1-4162-9318-b095b61695c0 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:06:58 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 13:16:03 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 13:16:12 [DEBUG] util.logger authenticate.py:55: employees authorization info : 98ae2685-f0d1-4162-9318-b095b61695c0 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:16:12 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 13:16:12 [ERROR] util.logger services.py:41: Failed to update services for employee c577aff1-b951-404d-84a9-8739a4c43917 - value of is_photo_editor is not boolean.
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\profile\update\services.py", line 18, in index
    is_photo_editor = validate_and_format_bool("is_photo_editor",data.get("is_photo_editor", None))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\aravind\lens35\util\regex.py", line 47, in validate_and_format_bool
    raise Exception("value of {} is not boolean.".format(str_name))
Exception: value of is_photo_editor is not boolean.

2023-03-16 13:16:12 [WARNING] django.request log.py:241: Bad Request: /employees/apis/profile/update/services
2023-03-16 13:16:23 [DEBUG] util.logger authenticate.py:55: employees authorization info : 98ae2685-f0d1-4162-9318-b095b61695c0 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:16:23 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 13:16:28 [DEBUG] util.logger authenticate.py:55: employees authorization info : 98ae2685-f0d1-4162-9318-b095b61695c0 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:16:28 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 13:16:28 [ERROR] util.logger services.py:41: Failed to update services for employee c577aff1-b951-404d-84a9-8739a4c43917 - is_photo_editor is Empty
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\profile\update\services.py", line 18, in index
    is_photo_editor = validate_and_format_bool("is_photo_editor",data.get("is_photo_editor", None))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\aravind\lens35\util\regex.py", line 39, in validate_and_format_bool
    raise Exception("{} is Empty".format(str_name))
Exception: is_photo_editor is Empty

2023-03-16 13:16:28 [WARNING] django.request log.py:241: Bad Request: /employees/apis/profile/update/services
2023-03-16 13:16:38 [DEBUG] util.logger authenticate.py:55: employees authorization info : 98ae2685-f0d1-4162-9318-b095b61695c0 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:16:38 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 13:16:51 [DEBUG] util.logger authenticate.py:55: employees authorization info : 98ae2685-f0d1-4162-9318-b095b61695c0 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:16:51 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 13:16:55 [DEBUG] util.logger authenticate.py:55: employees authorization info : 98ae2685-f0d1-4162-9318-b095b61695c0 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:16:55 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 13:16:55 [ERROR] util.logger services.py:41: Failed to update services for employee c577aff1-b951-404d-84a9-8739a4c43917 - Atlease one service must be added
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\profile\update\services.py", line 22, in index
    raise Exception("Atlease one service must be added")
Exception: Atlease one service must be added

2023-03-16 13:16:55 [WARNING] django.request log.py:241: Bad Request: /employees/apis/profile/update/services
2023-03-16 13:17:01 [DEBUG] util.logger authenticate.py:55: employees authorization info : 98ae2685-f0d1-4162-9318-b095b61695c0 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:17:01 [DEBUG] util.logger authenticate.py:80: Updated the token expiry
2023-03-16 13:30:31 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\apis\profile\update\services.py changed, reloading.
2023-03-16 13:30:31 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 13:32:04 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\apis\profile\update\basic_info.py changed, reloading.
2023-03-16 13:32:05 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 13:40:38 [DEBUG] util.logger authenticate.py:55: employees authorization info : 98ae2685-f0d1-4162-9318-b095b61695c0 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:40:38 [DEBUG] util.logger authenticate.py:75: Token is expired
2023-03-16 13:40:38 [WARNING] django.request log.py:241: Unauthorized: /employees/apis/profile/update/services
2023-03-16 13:41:01 [DEBUG] util.logger authenticate.py:55: employees authorization info : 98ae2685-f0d1-4162-9318-b095b61695c0 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:41:01 [WARNING] django.request log.py:241: Unauthorized: /employees/apis/profile/update/services
2023-03-16 13:41:17 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:41:17 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 13:41:17 [WARNING] django.request log.py:241: Not Found: /employees/apis/profile/update/portfolios
2023-03-16 13:41:47 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\api_urls.py changed, reloading.
2023-03-16 13:41:47 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 13:41:50 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:41:50 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 13:42:55 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:42:55 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 13:42:55 [ERROR] util.logger portfolios.py:23: Failed to update employee base location c577aff1-b951-404d-84a9-8739a4c43917 - JSON parse error - Expecting ',' delimiter: line 8 column 19 (char 170)
Traceback (most recent call last):
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\parsers.py", line 64, in parse
    return json.load(decoded_stream, parse_constant=parse_constant)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\utils\json.py", line 31, in load
    return json.load(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 8 column 19 (char 170)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\profile\update\portfolios.py", line 12, in index
    data = request.data
           ^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\request.py", line 216, in data
    self._load_data_and_files()
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\request.py", line 279, in _load_data_and_files
    self._data, self._files = self._parse()
                              ^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\request.py", line 354, in _parse
    parsed = parser.parse(stream, media_type, self.parser_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\parsers.py", line 66, in parse
    raise ParseError('JSON parse error - %s' % str(exc))
rest_framework.exceptions.ParseError: JSON parse error - Expecting ',' delimiter: line 8 column 19 (char 170)

2023-03-16 13:42:55 [WARNING] django.request log.py:241: Bad Request: /employees/apis/profile/update/portfolios
2023-03-16 13:43:01 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:43:02 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 13:43:53 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:43:53 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 13:43:53 [ERROR] util.logger portfolios.py:23: Failed to update employee base location c577aff1-b951-404d-84a9-8739a4c43917 - Portfolios cannot be empty
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\profile\update\portfolios.py", line 19, in index
    raise Exception("Portfolios cannot be empty")
Exception: Portfolios cannot be empty

2023-03-16 13:43:53 [WARNING] django.request log.py:241: Bad Request: /employees/apis/profile/update/portfolios
2023-03-16 13:44:00 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:44:00 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 13:44:42 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\apis\profile\update\portfolios.py changed, reloading.
2023-03-16 13:44:42 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 13:44:43 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\apis\profile\update\portfolios.py changed, reloading.
2023-03-16 13:44:44 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 13:44:50 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:44:50 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 13:44:50 [ERROR] util.logger portfolios.py:25: Failed to update employee base location c577aff1-b951-404d-84a9-8739a4c43917 - Portfolios cannot be empty..
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\profile\update\portfolios.py", line 17, in index
    raise Exception("Portfolios cannot be empty..")
Exception: Portfolios cannot be empty..

2023-03-16 13:44:50 [WARNING] django.request log.py:241: Bad Request: /employees/apis/profile/update/portfolios
2023-03-16 13:44:55 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:44:55 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 13:50:35 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\api_urls.py changed, reloading.
2023-03-16 13:50:36 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 13:51:30 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:51:30 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 13:51:34 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:51:34 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 13:54:10 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\util\regex.py changed, reloading.
2023-03-16 13:54:11 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 13:54:49 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\apis\profile\update\base_location.py changed, reloading.
2023-03-16 13:54:50 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 13:55:05 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\apis\profile\update\base_location.py changed, reloading.
2023-03-16 13:55:06 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 13:55:09 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:55:09 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 13:55:09 [ERROR] util.logger base_location.py:30: Failed to update employee base location c577aff1-b951-404d-84a9-8739a4c43917 - Invalid Pincode
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\profile\update\base_location.py", line 18, in index
    employee.base_location_pincode = validate_and_format_pincode(base_location_pincode)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\aravind\lens35\util\regex.py", line 15, in validate_and_format_pincode
    raise Exception("Invalid Pincode")
Exception: Invalid Pincode

2023-03-16 13:55:09 [WARNING] django.request log.py:241: Bad Request: /employees/apis/profile/update/baselocations
2023-03-16 13:55:16 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:55:16 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 13:55:24 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:55:24 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 13:55:24 [ERROR] util.logger base_location.py:30: Failed to update employee base location c577aff1-b951-404d-84a9-8739a4c43917 - Invalid Pincode
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\profile\update\base_location.py", line 18, in index
    employee.base_location_pincode = validate_and_format_pincode(base_location_pincode)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\aravind\lens35\util\regex.py", line 15, in validate_and_format_pincode
    raise Exception("Invalid Pincode")
Exception: Invalid Pincode

2023-03-16 13:55:24 [WARNING] django.request log.py:241: Bad Request: /employees/apis/profile/update/baselocations
2023-03-16 13:55:31 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:55:31 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 13:55:31 [ERROR] util.logger base_location.py:30: Failed to update employee base location c577aff1-b951-404d-84a9-8739a4c43917 - Invalid Pincode
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\profile\update\base_location.py", line 18, in index
    employee.base_location_pincode = validate_and_format_pincode(base_location_pincode)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\aravind\lens35\util\regex.py", line 15, in validate_and_format_pincode
    raise Exception("Invalid Pincode")
Exception: Invalid Pincode

2023-03-16 13:55:31 [WARNING] django.request log.py:241: Bad Request: /employees/apis/profile/update/baselocations
2023-03-16 13:55:37 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 13:55:37 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:08:17 [DEBUG] util.logger authenticate.py:55: employees authorization info : None | Identifier : None | Device ID : None
2023-03-16 14:08:17 [WARNING] django.request log.py:241: Unauthorized: /employees/apis/profile/update/mobile/requestotp
2023-03-16 14:08:45 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:08:45 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:08:45 [WARNING] django.request log.py:241: Not Found: /employees/apis/profile/update/mobile/requestotp
2023-03-16 14:09:24 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\api_urls.py changed, reloading.
2023-03-16 14:09:24 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 14:09:29 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:09:29 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:09:29 [WARNING] django.request log.py:241: Not Found: /employees/apis/profile/update/mobilenumber/requestotp/
2023-03-16 14:09:58 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:09:58 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:09:58 [WARNING] django.request log.py:241: Conflict: /employees/apis/profile/update/mobilenumber/requestotp
2023-03-16 14:10:14 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\api_urls.py changed, reloading.
2023-03-16 14:10:14 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 14:10:23 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:10:23 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:10:23 [WARNING] django.request log.py:241: Conflict: /employees/apis/profile/update/mobilenumber/requestotp/
2023-03-16 14:10:30 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:10:30 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:10:30 [WARNING] django.request log.py:241: Conflict: /employees/apis/profile/update/mobilenumber/requestotp/
2023-03-16 14:10:34 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:10:35 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:10:43 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:10:43 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:11:39 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\api_urls.py changed, reloading.
2023-03-16 14:11:40 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 14:14:13 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:14:14 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:14:14 [WARNING] django.request log.py:241: Conflict: /employees/apis/profile/fetch/mobilenumber/requestotp/
2023-03-16 14:14:19 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:14:19 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:14:19 [WARNING] django.request log.py:241: Conflict: /employees/apis/profile/fetch/mobilenumber/requestotp/
2023-03-16 14:15:02 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\apis\profile\fetch\request_otp_for_mobile_no_update.py changed, reloading.
2023-03-16 14:15:02 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 14:15:05 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:15:05 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:15:05 [WARNING] django.request log.py:241: Conflict: /employees/apis/profile/fetch/mobilenumber/requestotp/
2023-03-16 14:17:34 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:17:34 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:17:34 [WARNING] django.request log.py:241: Conflict: /employees/apis/profile/fetch/mobilenumber/requestotp/
2023-03-16 14:18:03 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\apis\profile\fetch\request_otp_for_mobile_no_update.py changed, reloading.
2023-03-16 14:18:04 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 14:18:07 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:18:07 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:18:07 [WARNING] django.request log.py:241: Conflict: /employees/apis/profile/fetch/mobilenumber/requestotp/
2023-03-16 14:19:08 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\apis\profile\fetch\request_otp_for_mobile_no_update.py changed, reloading.
2023-03-16 14:19:08 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 14:19:11 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:19:11 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:19:11 [ERROR] util.logger request_otp_for_mobile_no_update.py:35: 'UUID' object has no attribute 'strip'
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\profile\fetch\request_otp_for_mobile_no_update.py", line 26, in index
    if(employee.employee_id.strip() == employee_id.strip()):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'UUID' object has no attribute 'strip'

2023-03-16 14:19:11 [WARNING] django.request log.py:241: Bad Request: /employees/apis/profile/fetch/mobilenumber/requestotp/
2023-03-16 14:20:25 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\apis\profile\fetch\request_otp_for_mobile_no_update.py changed, reloading.
2023-03-16 14:20:25 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 14:20:27 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:20:27 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:20:27 [WARNING] django.request log.py:241: Conflict: /employees/apis/profile/fetch/mobilenumber/requestotp/
2023-03-16 14:21:57 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 14:22:02 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:22:02 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:22:02 [WARNING] django.request log.py:241: Expectation Failed: /employees/apis/profile/fetch/mobilenumber/requestotp/
2023-03-16 14:22:24 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\apis\profile\fetch\request_otp_for_mobile_no_update.py changed, reloading.
2023-03-16 14:22:24 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 14:23:30 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:23:30 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:29:32 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\api_urls.py changed, reloading.
2023-03-16 14:29:32 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 14:29:35 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:29:35 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:29:35 [ERROR] util.logger mobile_number.py:53: Failed : Invalid OTP
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\profile\update\mobile_number.py", line 21, in index
    otp = validate_and_format_otp(data.get("otp", None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\aravind\lens35\util\regex.py", line 23, in validate_and_format_otp
    raise Exception("Invalid OTP")
Exception: Invalid OTP

2023-03-16 14:29:35 [WARNING] django.request log.py:241: Bad Request: /employees/apis/profile/update/mobilenumber/
2023-03-16 14:29:50 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:29:50 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:29:54 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:29:54 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:29:54 [DEBUG] util.logger mobile_number.py:87: Creating new Employee record
2023-03-16 14:29:54 [ERROR] util.logger mobile_number.py:53: Failed : duplicate key value violates unique constraint "employees_mobile_number_key"
DETAIL:  Key (mobile_number)=(7767991695) already exists.

Traceback (most recent call last):
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "employees_mobile_number_key"
DETAIL:  Key (mobile_number)=(7767991695) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\profile\update\mobile_number.py", line 41, in index
    employee.save()
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 812, in save
    self.save_base(
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 863, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 976, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 1040, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1216, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: duplicate key value violates unique constraint "employees_mobile_number_key"
DETAIL:  Key (mobile_number)=(7767991695) already exists.


2023-03-16 14:29:54 [WARNING] django.request log.py:241: Bad Request: /employees/apis/profile/update/mobilenumber/
2023-03-16 14:33:03 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\apis\profile\update\mobile_number.py changed, reloading.
2023-03-16 14:33:04 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 14:34:10 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\apis\profile\update\mobile_number.py changed, reloading.
2023-03-16 14:34:11 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 14:34:22 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:34:22 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:34:22 [WARNING] django.request log.py:241: Conflict: /employees/apis/profile/fetch/mobilenumber/requestotp/
2023-03-16 14:34:31 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:34:31 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:34:42 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:34:42 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:34:50 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:34:50 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:37:55 [ERROR] util.logger generate_token_api.py:47: Failed : Invalid OTP
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\authenticate\generate_token_api.py", line 21, in index
    otp = validate_and_format_otp(data.get("otp", None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\aravind\lens35\util\regex.py", line 23, in validate_and_format_otp
    raise Exception("Invalid OTP")
Exception: Invalid OTP

2023-03-16 14:37:55 [WARNING] django.request log.py:241: Bad Request: /employees/apis/generate/token/
2023-03-16 14:38:20 [ERROR] util.logger generate_token_api.py:47: Failed : Invalid OTP
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\authenticate\generate_token_api.py", line 21, in index
    otp = validate_and_format_otp(data.get("otp", None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\aravind\lens35\util\regex.py", line 23, in validate_and_format_otp
    raise Exception("Invalid OTP")
Exception: Invalid OTP

2023-03-16 14:38:20 [WARNING] django.request log.py:241: Bad Request: /employees/apis/generate/token/
2023-03-16 14:39:57 [WARNING] django.request log.py:241: Too Many Requests: /employees/apis/generate/otp/
2023-03-16 14:40:18 [WARNING] django.request log.py:241: Too Many Requests: /employees/apis/generate/otp/
2023-03-16 14:40:36 [WARNING] django.request log.py:241: Too Many Requests: /employees/apis/generate/otp/
2023-03-16 14:41:01 [WARNING] django.request log.py:241: Too Many Requests: /employees/apis/generate/otp/
2023-03-16 14:41:13 [WARNING] django.request log.py:241: Too Many Requests: /employees/apis/generate/otp/
2023-03-16 14:43:34 [WARNING] django.request log.py:241: Too Many Requests: /employees/apis/generate/otp/
2023-03-16 14:44:09 [WARNING] django.request log.py:241: Unauthorized: /employees/apis/generate/token/
2023-03-16 14:45:51 [ERROR] util.logger generate_token_api.py:47: Failed : expected string or bytes-like object, got 'int'
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\authenticate\generate_token_api.py", line 21, in index
    otp = validate_and_format_otp(data.get("otp", None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\aravind\lens35\util\regex.py", line 20, in validate_and_format_otp
    if(re.findall("^[2-9]{1}[0-9]{5}$", otp)):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\re\__init__.py", line 216, in findall
    return _compile(pattern, flags).findall(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'int'

2023-03-16 14:45:51 [WARNING] django.request log.py:241: Bad Request: /employees/apis/generate/token/
2023-03-16 14:45:57 [WARNING] django.request log.py:241: Unauthorized: /employees/apis/generate/token/
2023-03-16 14:46:37 [WARNING] django.request log.py:241: Unauthorized: /employees/apis/generate/token/
2023-03-16 14:47:17 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 14:47:21 [WARNING] django.request log.py:241: Unauthorized: /employees/apis/generate/token/
2023-03-16 14:48:17 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\apis\authenticate\generate_token_api.py changed, reloading.
2023-03-16 14:48:17 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 14:48:19 [WARNING] django.request log.py:241: Unauthorized: /employees/apis/generate/token/
2023-03-16 14:48:59 [DEBUG] util.logger authenticate.py:55: employees authorization info : 5e69e7a3-1c05-4d70-a8f5-819c77dc3437 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:48:59 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:49:07 [DEBUG] util.logger authenticate.py:55: employees authorization info : 5e69e7a3-1c05-4d70-a8f5-819c77dc3437 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:49:07 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:49:12 [DEBUG] util.logger authenticate.py:55: employees authorization info : 5e69e7a3-1c05-4d70-a8f5-819c77dc3437 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:49:12 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:49:17 [DEBUG] util.logger authenticate.py:55: employees authorization info : 5e69e7a3-1c05-4d70-a8f5-819c77dc3437 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:49:17 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:49:22 [DEBUG] util.logger authenticate.py:55: employees authorization info : 5e69e7a3-1c05-4d70-a8f5-819c77dc3437 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:49:22 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:49:22 [WARNING] django.request log.py:241: Bad Request: /employees/apis/profile/update/mobilenumber/
2023-03-16 14:49:39 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:49:39 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:49:39 [WARNING] django.request log.py:241: Expectation Failed: /employees/apis/profile/fetch/mobilenumber/requestotp/
2023-03-16 14:49:44 [DEBUG] util.logger authenticate.py:55: employees authorization info : 50c1b4d2-42ab-4e35-bdb4-390ae6e81b13 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:49:44 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:49:47 [DEBUG] util.logger authenticate.py:55: employees authorization info : 5e69e7a3-1c05-4d70-a8f5-819c77dc3437 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:49:47 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 14:49:47 [WARNING] django.request log.py:241: Bad Request: /employees/apis/profile/update/mobilenumber/
2023-03-16 14:50:19 [DEBUG] util.logger authenticate.py:55: employees authorization info : 5e69e7a3-1c05-4d70-a8f5-819c77dc3437 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 14:50:19 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 15:01:06 [DEBUG] util.logger authenticate.py:55: employees authorization info : None | Identifier : None | Device ID : None
2023-03-16 15:01:06 [WARNING] django.request log.py:241: Unauthorized: /employees/apis/profile/fetch/presigned/url
2023-03-16 15:01:34 [DEBUG] util.logger authenticate.py:55: employees authorization info : 5e69e7a3-1c05-4d70-a8f5-819c77dc3437 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 15:01:34 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 15:01:34 [WARNING] django.request log.py:241: Not Found: /employees/apis/profile/fetch/presigned/url
2023-03-16 15:02:12 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\api_urls.py changed, reloading.
2023-03-16 15:02:12 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 15:06:43 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 15:06:46 [DEBUG] util.logger authenticate.py:55: employees authorization info : 5e69e7a3-1c05-4d70-a8f5-819c77dc3437 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 15:06:46 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 15:06:46 [WARNING] django.request log.py:241: Method Not Allowed: /employees/apis/profile/fetch/presigned/url/
2023-03-16 15:07:31 [DEBUG] util.logger authenticate.py:55: employees authorization info : 5e69e7a3-1c05-4d70-a8f5-819c77dc3437 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 15:07:31 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 15:07:31 [DEBUG] botocore.hooks hooks.py:483: Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2023-03-16 15:07:31 [DEBUG] botocore.hooks hooks.py:483: Changing event name from before-call.apigateway to before-call.api-gateway
2023-03-16 15:07:31 [DEBUG] botocore.hooks hooks.py:483: Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2023-03-16 15:07:31 [DEBUG] botocore.hooks hooks.py:483: Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2023-03-16 15:07:31 [DEBUG] botocore.hooks hooks.py:483: Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2023-03-16 15:07:31 [DEBUG] botocore.hooks hooks.py:483: Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2023-03-16 15:07:31 [DEBUG] botocore.hooks hooks.py:483: Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2023-03-16 15:07:31 [DEBUG] botocore.hooks hooks.py:483: Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2023-03-16 15:07:31 [DEBUG] botocore.hooks hooks.py:483: Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2023-03-16 15:07:31 [DEBUG] botocore.hooks hooks.py:483: Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2023-03-16 15:07:31 [DEBUG] botocore.hooks hooks.py:483: Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2023-03-16 15:07:31 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\endpoints.json
2023-03-16 15:07:31 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\sdk-default-configuration.json
2023-03-16 15:07:31 [DEBUG] botocore.hooks hooks.py:238: Event choose-service-name: calling handler <function handle_service_name_alias at 0x0000027A0FC7B920>
2023-03-16 15:07:31 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\s3\2006-03-01\service-2.json
2023-03-16 15:07:31 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\s3\2006-03-01\endpoint-rule-set-1.json.gz
2023-03-16 15:07:31 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\partitions.json
2023-03-16 15:07:31 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x0000027A0FBC9C60>
2023-03-16 15:07:31 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function lazy_call.<locals>._handler at 0x0000027A101237E0>
2023-03-16 15:07:31 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x0000027A0FBC99E0>
2023-03-16 15:07:31 [DEBUG] botocore.endpoint endpoint.py:408: Setting s3 timeout as (60, 60)
2023-03-16 15:07:31 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\_retry.json
2023-03-16 15:07:31 [DEBUG] botocore.client client.py:278: Registering retry handlers for service: s3
2023-03-16 15:07:31 [DEBUG] botocore.utils utils.py:1522: Registering S3 region redirector handler
2023-03-16 15:07:31 [DEBUG] botocore.hooks hooks.py:238: Event before-endpoint-resolution.s3: calling handler <function customize_endpoint_resolver_builtins at 0x0000027A0FC97740>
2023-03-16 15:07:31 [DEBUG] botocore.hooks hooks.py:238: Event before-endpoint-resolution.s3: calling handler <bound method S3RegionRedirectorv2.redirect_from_cache of <botocore.utils.S3RegionRedirectorv2 object at 0x0000027A109677D0>>
2023-03-16 15:07:31 [DEBUG] botocore.regions regions.py:498: Calling endpoint provider with parameters: {'Bucket': 'employees', 'Region': 'us-east-1', 'UseFIPS': False, 'UseDualStack': False, 'Endpoint': 'https://s3.ap-southeast-1.wasabisys.com', 'ForcePathStyle': True, 'Accelerate': False, 'UseGlobalEndpoint': True, 'DisableAccessPoints': True, 'DisableMultiRegionAccessPoints': False, 'UseArnRegion': True}
2023-03-16 15:07:31 [DEBUG] botocore.regions regions.py:513: Endpoint provider result: https://s3.ap-southeast-1.wasabisys.com/employees
2023-03-16 15:07:31 [DEBUG] botocore.regions regions.py:660: Selecting from endpoint provider's list of auth schemes: "sigv4". User selected auth scheme is: "None"
2023-03-16 15:07:31 [DEBUG] botocore.regions regions.py:733: Selected auth type "v4" as "v4" with signing context params: {'region': 'us-east-1', 'signing_name': 's3', 'disableDoubleEncoding': True}
2023-03-16 15:07:31 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.CreateBucket: calling handler <function validate_bucket_name at 0x0000027A0FC95440>
2023-03-16 15:07:31 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.CreateBucket: calling handler <function remove_bucket_from_url_paths_from_model at 0x0000027A0FC97560>
2023-03-16 15:07:31 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.CreateBucket: calling handler <bound method S3RegionRedirectorv2.annotate_request_context of <botocore.utils.S3RegionRedirectorv2 object at 0x0000027A109677D0>>
2023-03-16 15:07:31 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.CreateBucket: calling handler <function generate_idempotent_uuid at 0x0000027A0FC95260>
2023-03-16 15:07:31 [DEBUG] botocore.hooks hooks.py:238: Event choose-signer.s3.PutObject: calling handler <bound method ClientCreator._default_s3_presign_to_sigv2 of <botocore.client.ClientCreator object at 0x0000027A0FE982D0>>
2023-03-16 15:07:31 [DEBUG] botocore.hooks hooks.py:238: Event before-sign.s3.PutObject: calling handler <function remove_arn_from_signing_path at 0x0000027A0FC976A0>
2023-03-16 15:08:03 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\apis\profile\fetch\presigned_url.py changed, reloading.
2023-03-16 15:08:03 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 15:08:04 [DEBUG] util.logger authenticate.py:55: employees authorization info : 5e69e7a3-1c05-4d70-a8f5-819c77dc3437 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 15:08:04 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 15:08:04 [DEBUG] botocore.hooks hooks.py:483: Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2023-03-16 15:08:04 [DEBUG] botocore.hooks hooks.py:483: Changing event name from before-call.apigateway to before-call.api-gateway
2023-03-16 15:08:04 [DEBUG] botocore.hooks hooks.py:483: Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2023-03-16 15:08:04 [DEBUG] botocore.hooks hooks.py:483: Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2023-03-16 15:08:04 [DEBUG] botocore.hooks hooks.py:483: Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2023-03-16 15:08:04 [DEBUG] botocore.hooks hooks.py:483: Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2023-03-16 15:08:04 [DEBUG] botocore.hooks hooks.py:483: Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2023-03-16 15:08:04 [DEBUG] botocore.hooks hooks.py:483: Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2023-03-16 15:08:04 [DEBUG] botocore.hooks hooks.py:483: Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2023-03-16 15:08:04 [DEBUG] botocore.hooks hooks.py:483: Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2023-03-16 15:08:04 [DEBUG] botocore.hooks hooks.py:483: Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2023-03-16 15:08:04 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\endpoints.json
2023-03-16 15:08:04 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\sdk-default-configuration.json
2023-03-16 15:08:04 [DEBUG] botocore.hooks hooks.py:238: Event choose-service-name: calling handler <function handle_service_name_alias at 0x000001DBEF7774C0>
2023-03-16 15:08:04 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\s3\2006-03-01\service-2.json
2023-03-16 15:08:04 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\s3\2006-03-01\endpoint-rule-set-1.json.gz
2023-03-16 15:08:04 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\partitions.json
2023-03-16 15:08:04 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x000001DBEF6C1800>
2023-03-16 15:08:04 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function lazy_call.<locals>._handler at 0x000001DBEFA4FE20>
2023-03-16 15:08:04 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x000001DBEF6C1580>
2023-03-16 15:08:04 [DEBUG] botocore.endpoint endpoint.py:408: Setting s3 timeout as (60, 60)
2023-03-16 15:08:04 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\_retry.json
2023-03-16 15:08:04 [DEBUG] botocore.client client.py:278: Registering retry handlers for service: s3
2023-03-16 15:08:04 [DEBUG] botocore.utils utils.py:1522: Registering S3 region redirector handler
2023-03-16 15:08:04 [DEBUG] botocore.hooks hooks.py:238: Event before-endpoint-resolution.s3: calling handler <function customize_endpoint_resolver_builtins at 0x000001DBEF7932E0>
2023-03-16 15:08:04 [DEBUG] botocore.hooks hooks.py:238: Event before-endpoint-resolution.s3: calling handler <bound method S3RegionRedirectorv2.redirect_from_cache of <botocore.utils.S3RegionRedirectorv2 object at 0x000001DBF13C3990>>
2023-03-16 15:08:04 [DEBUG] botocore.regions regions.py:498: Calling endpoint provider with parameters: {'Bucket': 'employees', 'Region': 'us-east-1', 'UseFIPS': False, 'UseDualStack': False, 'Endpoint': 'https://s3.ap-southeast-1.wasabisys.com', 'ForcePathStyle': True, 'Accelerate': False, 'UseGlobalEndpoint': True, 'DisableAccessPoints': True, 'DisableMultiRegionAccessPoints': False, 'UseArnRegion': True}
2023-03-16 15:08:04 [DEBUG] botocore.regions regions.py:513: Endpoint provider result: https://s3.ap-southeast-1.wasabisys.com/employees
2023-03-16 15:08:04 [DEBUG] botocore.regions regions.py:660: Selecting from endpoint provider's list of auth schemes: "sigv4". User selected auth scheme is: "None"
2023-03-16 15:08:04 [DEBUG] botocore.regions regions.py:733: Selected auth type "v4" as "v4" with signing context params: {'region': 'us-east-1', 'signing_name': 's3', 'disableDoubleEncoding': True}
2023-03-16 15:08:04 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.CreateBucket: calling handler <function validate_bucket_name at 0x000001DBEF790FE0>
2023-03-16 15:08:04 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.CreateBucket: calling handler <function remove_bucket_from_url_paths_from_model at 0x000001DBEF793100>
2023-03-16 15:08:04 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.CreateBucket: calling handler <bound method S3RegionRedirectorv2.annotate_request_context of <botocore.utils.S3RegionRedirectorv2 object at 0x000001DBF13C3990>>
2023-03-16 15:08:04 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.CreateBucket: calling handler <function generate_idempotent_uuid at 0x000001DBEF790E00>
2023-03-16 15:08:04 [DEBUG] botocore.hooks hooks.py:238: Event choose-signer.s3.PutObject: calling handler <bound method ClientCreator._default_s3_presign_to_sigv2 of <botocore.client.ClientCreator object at 0x000001DBEF82B410>>
2023-03-16 15:08:04 [DEBUG] botocore.hooks hooks.py:238: Event before-sign.s3.PutObject: calling handler <function remove_arn_from_signing_path at 0x000001DBEF793240>
2023-03-16 15:08:06 [DEBUG] util.logger authenticate.py:55: employees authorization info : 5e69e7a3-1c05-4d70-a8f5-819c77dc3437 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 15:08:07 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 15:08:07 [DEBUG] botocore.hooks hooks.py:238: Event choose-service-name: calling handler <function handle_service_name_alias at 0x000001DBEF7774C0>
2023-03-16 15:08:07 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x000001DBEF6C1800>
2023-03-16 15:08:07 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function lazy_call.<locals>._handler at 0x000001DBEFA4FE20>
2023-03-16 15:08:07 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x000001DBEF6C1580>
2023-03-16 15:08:07 [DEBUG] botocore.endpoint endpoint.py:408: Setting s3 timeout as (60, 60)
2023-03-16 15:08:07 [DEBUG] botocore.client client.py:278: Registering retry handlers for service: s3
2023-03-16 15:08:07 [DEBUG] botocore.utils utils.py:1522: Registering S3 region redirector handler
2023-03-16 15:08:07 [DEBUG] botocore.hooks hooks.py:238: Event before-endpoint-resolution.s3: calling handler <function customize_endpoint_resolver_builtins at 0x000001DBEF7932E0>
2023-03-16 15:08:07 [DEBUG] botocore.hooks hooks.py:238: Event before-endpoint-resolution.s3: calling handler <bound method S3RegionRedirectorv2.redirect_from_cache of <botocore.utils.S3RegionRedirectorv2 object at 0x000001DBF157F090>>
2023-03-16 15:08:07 [DEBUG] botocore.regions regions.py:498: Calling endpoint provider with parameters: {'Bucket': 'employees', 'Region': 'us-east-1', 'UseFIPS': False, 'UseDualStack': False, 'Endpoint': 'https://s3.ap-southeast-1.wasabisys.com', 'ForcePathStyle': True, 'Accelerate': False, 'UseGlobalEndpoint': True, 'DisableAccessPoints': True, 'DisableMultiRegionAccessPoints': False, 'UseArnRegion': True}
2023-03-16 15:08:07 [DEBUG] botocore.regions regions.py:513: Endpoint provider result: https://s3.ap-southeast-1.wasabisys.com/employees
2023-03-16 15:08:07 [DEBUG] botocore.regions regions.py:660: Selecting from endpoint provider's list of auth schemes: "sigv4". User selected auth scheme is: "None"
2023-03-16 15:08:07 [DEBUG] botocore.regions regions.py:733: Selected auth type "v4" as "v4" with signing context params: {'region': 'us-east-1', 'signing_name': 's3', 'disableDoubleEncoding': True}
2023-03-16 15:08:07 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.CreateBucket: calling handler <function validate_bucket_name at 0x000001DBEF790FE0>
2023-03-16 15:08:07 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.CreateBucket: calling handler <function remove_bucket_from_url_paths_from_model at 0x000001DBEF793100>
2023-03-16 15:08:07 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.CreateBucket: calling handler <bound method S3RegionRedirectorv2.annotate_request_context of <botocore.utils.S3RegionRedirectorv2 object at 0x000001DBF157F090>>
2023-03-16 15:08:07 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.CreateBucket: calling handler <function generate_idempotent_uuid at 0x000001DBEF790E00>
2023-03-16 15:08:07 [DEBUG] botocore.hooks hooks.py:238: Event choose-signer.s3.PutObject: calling handler <bound method ClientCreator._default_s3_presign_to_sigv2 of <botocore.client.ClientCreator object at 0x000001DBF13AD990>>
2023-03-16 15:08:07 [DEBUG] botocore.hooks hooks.py:238: Event before-sign.s3.PutObject: calling handler <function remove_arn_from_signing_path at 0x000001DBEF793240>
2023-03-16 15:09:24 [DEBUG] util.logger authenticate.py:55: employees authorization info : 5e69e7a3-1c05-4d70-a8f5-819c77dc3437 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 15:09:24 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 15:20:41 [DEBUG] util.logger authenticate.py:55: employees authorization info : 5e69e7a3-1c05-4d70-a8f5-819c77dc3437 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 15:20:41 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 15:20:54 [DEBUG] util.logger authenticate.py:55: employees authorization info : 5e69e7a3-1c05-4d70-a8f5-819c77dc3437 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 15:20:54 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 15:21:22 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\apis\profile\update\mobile_number.py changed, reloading.
2023-03-16 15:21:23 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 15:26:08 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\api_urls.py changed, reloading.
2023-03-16 15:26:08 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 15:27:14 [DEBUG] util.logger authenticate.py:55: employees authorization info : 5e69e7a3-1c05-4d70-a8f5-819c77dc3437 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 15:27:14 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 15:27:14 [DEBUG] botocore.hooks hooks.py:483: Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2023-03-16 15:27:14 [DEBUG] botocore.hooks hooks.py:483: Changing event name from before-call.apigateway to before-call.api-gateway
2023-03-16 15:27:14 [DEBUG] botocore.hooks hooks.py:483: Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2023-03-16 15:27:14 [DEBUG] botocore.hooks hooks.py:483: Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2023-03-16 15:27:14 [DEBUG] botocore.hooks hooks.py:483: Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2023-03-16 15:27:14 [DEBUG] botocore.hooks hooks.py:483: Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2023-03-16 15:27:14 [DEBUG] botocore.hooks hooks.py:483: Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2023-03-16 15:27:14 [DEBUG] botocore.hooks hooks.py:483: Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2023-03-16 15:27:14 [DEBUG] botocore.hooks hooks.py:483: Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2023-03-16 15:27:14 [DEBUG] botocore.hooks hooks.py:483: Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2023-03-16 15:27:14 [DEBUG] botocore.hooks hooks.py:483: Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2023-03-16 15:27:14 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\endpoints.json
2023-03-16 15:27:14 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\sdk-default-configuration.json
2023-03-16 15:27:14 [DEBUG] botocore.hooks hooks.py:238: Event choose-service-name: calling handler <function handle_service_name_alias at 0x00000196042E74C0>
2023-03-16 15:27:14 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\s3\2006-03-01\service-2.json
2023-03-16 15:27:14 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\s3\2006-03-01\endpoint-rule-set-1.json.gz
2023-03-16 15:27:14 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\partitions.json
2023-03-16 15:27:14 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x0000019604235800>
2023-03-16 15:27:14 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function lazy_call.<locals>._handler at 0x00000196047D4EA0>
2023-03-16 15:27:14 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x0000019604235580>
2023-03-16 15:27:14 [DEBUG] botocore.endpoint endpoint.py:408: Setting s3 timeout as (60, 60)
2023-03-16 15:27:14 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\_retry.json
2023-03-16 15:27:14 [DEBUG] botocore.client client.py:278: Registering retry handlers for service: s3
2023-03-16 15:27:14 [DEBUG] botocore.utils utils.py:1522: Registering S3 region redirector handler
2023-03-16 15:27:14 [DEBUG] botocore.hooks hooks.py:238: Event before-endpoint-resolution.s3: calling handler <function customize_endpoint_resolver_builtins at 0x00000196043032E0>
2023-03-16 15:27:14 [DEBUG] botocore.hooks hooks.py:238: Event before-endpoint-resolution.s3: calling handler <bound method S3RegionRedirectorv2.redirect_from_cache of <botocore.utils.S3RegionRedirectorv2 object at 0x000001960610F610>>
2023-03-16 15:27:14 [DEBUG] botocore.regions regions.py:498: Calling endpoint provider with parameters: {'Bucket': 'employees', 'Region': 'us-east-1', 'UseFIPS': False, 'UseDualStack': False, 'Endpoint': 'https://s3.ap-southeast-1.wasabisys.com', 'ForcePathStyle': True, 'Accelerate': False, 'UseGlobalEndpoint': True, 'DisableMultiRegionAccessPoints': False, 'UseArnRegion': True}
2023-03-16 15:27:14 [DEBUG] botocore.regions regions.py:513: Endpoint provider result: https://s3.ap-southeast-1.wasabisys.com/employees
2023-03-16 15:27:14 [DEBUG] botocore.regions regions.py:660: Selecting from endpoint provider's list of auth schemes: "sigv4". User selected auth scheme is: "None"
2023-03-16 15:27:14 [DEBUG] botocore.regions regions.py:733: Selected auth type "v4" as "v4" with signing context params: {'region': 'us-east-1', 'signing_name': 's3', 'disableDoubleEncoding': True}
2023-03-16 15:27:14 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.GetObject: calling handler <function sse_md5 at 0x0000019604301080>
2023-03-16 15:27:14 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.GetObject: calling handler <function validate_bucket_name at 0x0000019604300FE0>
2023-03-16 15:27:14 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.GetObject: calling handler <function remove_bucket_from_url_paths_from_model at 0x0000019604303100>
2023-03-16 15:27:14 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.GetObject: calling handler <bound method S3RegionRedirectorv2.annotate_request_context of <botocore.utils.S3RegionRedirectorv2 object at 0x000001960610F610>>
2023-03-16 15:27:14 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.GetObject: calling handler <function generate_idempotent_uuid at 0x0000019604300E00>
2023-03-16 15:27:14 [DEBUG] botocore.utils utils.py:943: Unable to parse timestamp with "tzlocal" timezone info.
Traceback (most recent call last):
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\utils.py", line 941, in parse_timestamp
    return _parse_timestamp_with_tzinfo(value, tzinfo)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\utils.py", line 912, in _parse_timestamp_with_tzinfo
    return datetime.datetime.fromtimestamp(value, tzinfo())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 144, in fromutc
    return f(self, dt)
           ^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 258, in fromutc
    dt_wall = self._fromutc(dt)
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 222, in _fromutc
    dtoff = dt.utcoffset()
            ^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 222, in utcoffset
    if self._isdst(dt):
       ^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 294, in _isdst
    if self.is_ambiguous(dt):
       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 256, in is_ambiguous
    (naive_dst != self._naive_is_dst(dt - self._dst_saved)))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 260, in _naive_is_dst
    return time.localtime(timestamp + time.timezone).tm_isdst
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
2023-03-16 15:27:14 [DEBUG] botocore.utils utils.py:943: Unable to parse timestamp with "tzlocal" timezone info.
Traceback (most recent call last):
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\utils.py", line 941, in parse_timestamp
    return _parse_timestamp_with_tzinfo(value, tzinfo)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\utils.py", line 912, in _parse_timestamp_with_tzinfo
    return datetime.datetime.fromtimestamp(value, tzinfo())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 144, in fromutc
    return f(self, dt)
           ^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 258, in fromutc
    dt_wall = self._fromutc(dt)
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 222, in _fromutc
    dtoff = dt.utcoffset()
            ^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 222, in utcoffset
    if self._isdst(dt):
       ^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 294, in _isdst
    if self.is_ambiguous(dt):
       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 256, in is_ambiguous
    (naive_dst != self._naive_is_dst(dt - self._dst_saved)))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 260, in _naive_is_dst
    return time.localtime(timestamp + time.timezone).tm_isdst
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
2023-03-16 15:27:14 [DEBUG] botocore.hooks hooks.py:238: Event choose-signer.s3.GetObject: calling handler <bound method ClientCreator._default_s3_presign_to_sigv2 of <botocore.client.ClientCreator object at 0x00000196047E71D0>>
2023-03-16 15:27:14 [DEBUG] botocore.hooks hooks.py:238: Event before-sign.s3.GetObject: calling handler <function remove_arn_from_signing_path at 0x0000019604303240>
2023-03-16 15:27:14 [DEBUG] botocore.auth auth.py:830: Calculating signature using hmacv1 auth.
2023-03-16 15:27:14 [DEBUG] botocore.auth auth.py:832: HTTP request method: GET
2023-03-16 15:27:14 [DEBUG] botocore.auth auth.py:824: StringToSign:
GET


1678984034
/employees/dp/71c276d6-ab46-4edf-a12c-032ee0eebab3.jpg?response-expires=Thu, 01 Jan 1970 00:00:30 GMT
2023-03-16 15:27:25 [DEBUG] util.logger authenticate.py:55: employees authorization info : 5e69e7a3-1c05-4d70-a8f5-819c77dc3437 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 15:27:25 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 15:27:25 [DEBUG] botocore.hooks hooks.py:238: Event choose-service-name: calling handler <function handle_service_name_alias at 0x00000196042E74C0>
2023-03-16 15:27:25 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x0000019604235800>
2023-03-16 15:27:25 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function lazy_call.<locals>._handler at 0x00000196047D4EA0>
2023-03-16 15:27:25 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x0000019604235580>
2023-03-16 15:27:25 [DEBUG] botocore.endpoint endpoint.py:408: Setting s3 timeout as (60, 60)
2023-03-16 15:27:25 [DEBUG] botocore.client client.py:278: Registering retry handlers for service: s3
2023-03-16 15:27:25 [DEBUG] botocore.utils utils.py:1522: Registering S3 region redirector handler
2023-03-16 15:27:25 [DEBUG] botocore.hooks hooks.py:238: Event before-endpoint-resolution.s3: calling handler <function customize_endpoint_resolver_builtins at 0x00000196043032E0>
2023-03-16 15:27:25 [DEBUG] botocore.hooks hooks.py:238: Event before-endpoint-resolution.s3: calling handler <bound method S3RegionRedirectorv2.redirect_from_cache of <botocore.utils.S3RegionRedirectorv2 object at 0x00000196062DC110>>
2023-03-16 15:27:25 [DEBUG] botocore.regions regions.py:498: Calling endpoint provider with parameters: {'Bucket': 'employees', 'Region': 'us-east-1', 'UseFIPS': False, 'UseDualStack': False, 'Endpoint': 'https://s3.ap-southeast-1.wasabisys.com', 'ForcePathStyle': True, 'Accelerate': False, 'UseGlobalEndpoint': True, 'DisableMultiRegionAccessPoints': False, 'UseArnRegion': True}
2023-03-16 15:27:25 [DEBUG] botocore.regions regions.py:513: Endpoint provider result: https://s3.ap-southeast-1.wasabisys.com/employees
2023-03-16 15:27:25 [DEBUG] botocore.regions regions.py:660: Selecting from endpoint provider's list of auth schemes: "sigv4". User selected auth scheme is: "None"
2023-03-16 15:27:25 [DEBUG] botocore.regions regions.py:733: Selected auth type "v4" as "v4" with signing context params: {'region': 'us-east-1', 'signing_name': 's3', 'disableDoubleEncoding': True}
2023-03-16 15:27:25 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.DeleteObject: calling handler <function validate_bucket_name at 0x0000019604300FE0>
2023-03-16 15:27:25 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.DeleteObject: calling handler <function remove_bucket_from_url_paths_from_model at 0x0000019604303100>
2023-03-16 15:27:25 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.DeleteObject: calling handler <bound method S3RegionRedirectorv2.annotate_request_context of <botocore.utils.S3RegionRedirectorv2 object at 0x00000196062DC110>>
2023-03-16 15:27:25 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.DeleteObject: calling handler <function generate_idempotent_uuid at 0x0000019604300E00>
2023-03-16 15:27:25 [DEBUG] botocore.hooks hooks.py:238: Event before-call.s3.DeleteObject: calling handler <function add_expect_header at 0x00000196043013A0>
2023-03-16 15:27:25 [DEBUG] botocore.hooks hooks.py:238: Event before-call.s3.DeleteObject: calling handler <function add_recursion_detection_header at 0x00000196042E7600>
2023-03-16 15:27:25 [DEBUG] botocore.hooks hooks.py:238: Event before-call.s3.DeleteObject: calling handler <function inject_api_version_header_if_needed at 0x00000196043028E0>
2023-03-16 15:27:25 [DEBUG] botocore.endpoint endpoint.py:114: Making request for OperationModel(name=DeleteObject) with params: {'url_path': '/dp/71c276d6-ab46-4edf-a12c-032ee0eebab3.jpg', 'query_string': {}, 'method': 'DELETE', 'headers': {'User-Agent': 'Boto3/1.26.92 Python/3.11.1 Windows/10 Botocore/1.29.92'}, 'body': b'', 'auth_path': '/employees/dp/71c276d6-ab46-4edf-a12c-032ee0eebab3.jpg', 'url': 'https://s3.ap-southeast-1.wasabisys.com/employees/dp/71c276d6-ab46-4edf-a12c-032ee0eebab3.jpg', 'context': {'client_region': 'us-east-1', 'client_config': <botocore.config.Config object at 0x000001960610C290>, 'has_streaming_input': False, 'auth_type': 'v4', 'signing': {'region': 'us-east-1', 'signing_name': 's3', 'disableDoubleEncoding': True}, 's3_redirect': {'redirected': False, 'bucket': 'employees', 'params': {'Bucket': 'employees', 'Key': 'dp/71c276d6-ab46-4edf-a12c-032ee0eebab3.jpg'}}}}
2023-03-16 15:27:25 [DEBUG] botocore.hooks hooks.py:238: Event request-created.s3.DeleteObject: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x000001960610F510>>
2023-03-16 15:27:25 [DEBUG] botocore.hooks hooks.py:238: Event choose-signer.s3.DeleteObject: calling handler <bound method ClientCreator._default_s3_presign_to_sigv2 of <botocore.client.ClientCreator object at 0x00000196047E6510>>
2023-03-16 15:27:25 [DEBUG] botocore.hooks hooks.py:238: Event choose-signer.s3.DeleteObject: calling handler <function set_operation_specific_signer at 0x0000019604300CC0>
2023-03-16 15:27:25 [DEBUG] botocore.hooks hooks.py:238: Event before-sign.s3.DeleteObject: calling handler <function remove_arn_from_signing_path at 0x0000019604303240>
2023-03-16 15:27:25 [DEBUG] botocore.auth auth.py:425: Calculating signature using v4 auth.
2023-03-16 15:27:25 [DEBUG] botocore.auth auth.py:426: CanonicalRequest:
DELETE
/employees/dp/71c276d6-ab46-4edf-a12c-032ee0eebab3.jpg

host:s3.ap-southeast-1.wasabisys.com
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20230316T152725Z

host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2023-03-16 15:27:25 [DEBUG] botocore.auth auth.py:428: StringToSign:
AWS4-HMAC-SHA256
20230316T152725Z
20230316/us-east-1/s3/aws4_request
581c5e28d2da21778d4dfb56bbdcbb75add08f6ba210f7ad09d76e6652c20605
2023-03-16 15:27:25 [DEBUG] botocore.auth auth.py:430: Signature:
d615b0e8150ad81cd326080784a7c2d1278ef04333d23673a4f0f56b07d301ca
2023-03-16 15:27:25 [DEBUG] botocore.hooks hooks.py:238: Event request-created.s3.DeleteObject: calling handler <function add_retry_headers at 0x0000019604303060>
2023-03-16 15:27:25 [DEBUG] botocore.endpoint endpoint.py:265: Sending http request: <AWSPreparedRequest stream_output=False, method=DELETE, url=https://s3.ap-southeast-1.wasabisys.com/employees/dp/71c276d6-ab46-4edf-a12c-032ee0eebab3.jpg, headers={'User-Agent': b'Boto3/1.26.92 Python/3.11.1 Windows/10 Botocore/1.29.92', 'X-Amz-Date': b'20230316T152725Z', 'X-Amz-Content-SHA256': b'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'Authorization': b'AWS4-HMAC-SHA256 Credential=C3DQUWUT8FKRKY0IKQ88/20230316/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=d615b0e8150ad81cd326080784a7c2d1278ef04333d23673a4f0f56b07d301ca', 'amz-sdk-invocation-id': b'afc64dd7-653b-49d1-a94b-97ecaf57263f', 'amz-sdk-request': b'attempt=1', 'Content-Length': '0'}>
2023-03-16 15:27:25 [DEBUG] botocore.httpsession httpsession.py:90: Certificate path: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\cacert.pem
2023-03-16 15:27:25 [DEBUG] urllib3.connectionpool connectionpool.py:1003: Starting new HTTPS connection (1): s3.ap-southeast-1.wasabisys.com:443
2023-03-16 15:27:27 [DEBUG] urllib3.connectionpool connectionpool.py:456: https://s3.ap-southeast-1.wasabisys.com:443 "DELETE /employees/dp/71c276d6-ab46-4edf-a12c-032ee0eebab3.jpg HTTP/1.1" 403 None
2023-03-16 15:27:27 [DEBUG] botocore.parsers parsers.py:240: Response headers: {'Content-Type': 'application/xml', 'Date': 'Thu, 16 Mar 2023 15:27:26 GMT', 'Server': 'WasabiS3/7.12.1004-2023-02-17-7ff2f5bdd9 (head1)', 'x-amz-id-2': 'a9EPSMR6lr0Mcq1mq18dqDYEXqtus9MrWI34etQcsg9c9Vuwh+rofsAz0+Lr+n1/68zRX36kSklB', 'x-amz-request-id': 'A41D4E42B993F625', 'Transfer-Encoding': 'chunked'}
2023-03-16 15:27:27 [DEBUG] botocore.parsers parsers.py:241: Response body:
b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>PoorAccountStanding</Code><Message>Could not perform operation because of poor account standing or trial period expiry. Please have your Wasabi account administrator update billing information for the account.</Message><OwnerAccountCanonicalId>C1AE454B95E45DE92E1E96976FF1A0E2EFB08EB789D5C697810475735DDE5987</OwnerAccountCanonicalId><RequestId>A41D4E42B993F625</RequestId><HostId>a9EPSMR6lr0Mcq1mq18dqDYEXqtus9MrWI34etQcsg9c9Vuwh+rofsAz0+Lr+n1/68zRX36kSklB</HostId></Error>'
2023-03-16 15:27:27 [DEBUG] botocore.hooks hooks.py:238: Event needs-retry.s3.DeleteObject: calling handler <botocore.retryhandler.RetryHandler object at 0x0000019605C26650>
2023-03-16 15:27:27 [DEBUG] botocore.retryhandler retryhandler.py:211: No retry needed.
2023-03-16 15:27:27 [DEBUG] botocore.hooks hooks.py:238: Event needs-retry.s3.DeleteObject: calling handler <bound method S3RegionRedirectorv2.redirect_from_error of <botocore.utils.S3RegionRedirectorv2 object at 0x00000196062DC110>>
2023-03-16 15:27:27 [ERROR] util.logger profile_picture.py:35: Failed to update display picture for employee c577aff1-b951-404d-84a9-8739a4c43917 - An error occurred (PoorAccountStanding) when calling the DeleteObject operation: Could not perform operation because of poor account standing or trial period expiry. Please have your Wasabi account administrator update billing information for the account.
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\profile\update\profile_picture.py", line 24, in index
    delete_file_from_bucket(EMPLOYEES_BUCKET, EMPLOYEES_DP_FOLDER, employee.display_picture)
  File "C:\aravind\lens35\util\wasabi.py", line 40, in delete_file_from_bucket
    s3.delete_object(Bucket=bucket_name, Key=key)
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (PoorAccountStanding) when calling the DeleteObject operation: Could not perform operation because of poor account standing or trial period expiry. Please have your Wasabi account administrator update billing information for the account.

2023-03-16 15:27:27 [WARNING] django.request log.py:241: Bad Request: /employees/apis/profile/update/profilepicture/
2023-03-16 15:28:42 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\apis\profile\update\profile_picture.py changed, reloading.
2023-03-16 15:28:42 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 15:28:43 [DEBUG] util.logger authenticate.py:55: employees authorization info : 5e69e7a3-1c05-4d70-a8f5-819c77dc3437 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 15:28:43 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 15:28:51 [DEBUG] util.logger authenticate.py:55: employees authorization info : 5e69e7a3-1c05-4d70-a8f5-819c77dc3437 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 15:28:51 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 15:28:51 [DEBUG] botocore.hooks hooks.py:483: Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2023-03-16 15:28:51 [DEBUG] botocore.hooks hooks.py:483: Changing event name from before-call.apigateway to before-call.api-gateway
2023-03-16 15:28:51 [DEBUG] botocore.hooks hooks.py:483: Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2023-03-16 15:28:51 [DEBUG] botocore.hooks hooks.py:483: Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2023-03-16 15:28:51 [DEBUG] botocore.hooks hooks.py:483: Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2023-03-16 15:28:51 [DEBUG] botocore.hooks hooks.py:483: Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2023-03-16 15:28:51 [DEBUG] botocore.hooks hooks.py:483: Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2023-03-16 15:28:51 [DEBUG] botocore.hooks hooks.py:483: Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2023-03-16 15:28:51 [DEBUG] botocore.hooks hooks.py:483: Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2023-03-16 15:28:51 [DEBUG] botocore.hooks hooks.py:483: Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2023-03-16 15:28:51 [DEBUG] botocore.hooks hooks.py:483: Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2023-03-16 15:28:51 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\endpoints.json
2023-03-16 15:28:51 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\sdk-default-configuration.json
2023-03-16 15:28:51 [DEBUG] botocore.hooks hooks.py:238: Event choose-service-name: calling handler <function handle_service_name_alias at 0x00000270D10074C0>
2023-03-16 15:28:51 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\s3\2006-03-01\service-2.json
2023-03-16 15:28:51 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\s3\2006-03-01\endpoint-rule-set-1.json.gz
2023-03-16 15:28:51 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\partitions.json
2023-03-16 15:28:51 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x00000270D0F51800>
2023-03-16 15:28:51 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function lazy_call.<locals>._handler at 0x00000270D12CF420>
2023-03-16 15:28:52 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x00000270D0F51580>
2023-03-16 15:28:52 [DEBUG] botocore.endpoint endpoint.py:408: Setting s3 timeout as (60, 60)
2023-03-16 15:28:52 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\_retry.json
2023-03-16 15:28:52 [DEBUG] botocore.client client.py:278: Registering retry handlers for service: s3
2023-03-16 15:28:52 [DEBUG] botocore.utils utils.py:1522: Registering S3 region redirector handler
2023-03-16 15:28:52 [DEBUG] botocore.hooks hooks.py:238: Event before-endpoint-resolution.s3: calling handler <function customize_endpoint_resolver_builtins at 0x00000270D10232E0>
2023-03-16 15:28:52 [DEBUG] botocore.hooks hooks.py:238: Event before-endpoint-resolution.s3: calling handler <bound method S3RegionRedirectorv2.redirect_from_cache of <botocore.utils.S3RegionRedirectorv2 object at 0x00000270D2CFF610>>
2023-03-16 15:28:52 [DEBUG] botocore.regions regions.py:498: Calling endpoint provider with parameters: {'Bucket': 'employees', 'Region': 'us-east-1', 'UseFIPS': False, 'UseDualStack': False, 'Endpoint': 'https://s3.ap-southeast-1.wasabisys.com', 'ForcePathStyle': True, 'Accelerate': False, 'UseGlobalEndpoint': True, 'DisableMultiRegionAccessPoints': False, 'UseArnRegion': True}
2023-03-16 15:28:52 [DEBUG] botocore.regions regions.py:513: Endpoint provider result: https://s3.ap-southeast-1.wasabisys.com/employees
2023-03-16 15:28:52 [DEBUG] botocore.regions regions.py:660: Selecting from endpoint provider's list of auth schemes: "sigv4". User selected auth scheme is: "None"
2023-03-16 15:28:52 [DEBUG] botocore.regions regions.py:733: Selected auth type "v4" as "v4" with signing context params: {'region': 'us-east-1', 'signing_name': 's3', 'disableDoubleEncoding': True}
2023-03-16 15:28:52 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.GetObject: calling handler <function sse_md5 at 0x00000270D1021080>
2023-03-16 15:28:52 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.GetObject: calling handler <function validate_bucket_name at 0x00000270D1020FE0>
2023-03-16 15:28:52 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.GetObject: calling handler <function remove_bucket_from_url_paths_from_model at 0x00000270D1023100>
2023-03-16 15:28:52 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.GetObject: calling handler <bound method S3RegionRedirectorv2.annotate_request_context of <botocore.utils.S3RegionRedirectorv2 object at 0x00000270D2CFF610>>
2023-03-16 15:28:52 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.GetObject: calling handler <function generate_idempotent_uuid at 0x00000270D1020E00>
2023-03-16 15:28:52 [DEBUG] botocore.utils utils.py:943: Unable to parse timestamp with "tzlocal" timezone info.
Traceback (most recent call last):
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\utils.py", line 941, in parse_timestamp
    return _parse_timestamp_with_tzinfo(value, tzinfo)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\utils.py", line 912, in _parse_timestamp_with_tzinfo
    return datetime.datetime.fromtimestamp(value, tzinfo())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 144, in fromutc
    return f(self, dt)
           ^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 258, in fromutc
    dt_wall = self._fromutc(dt)
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 222, in _fromutc
    dtoff = dt.utcoffset()
            ^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 222, in utcoffset
    if self._isdst(dt):
       ^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 294, in _isdst
    if self.is_ambiguous(dt):
       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 256, in is_ambiguous
    (naive_dst != self._naive_is_dst(dt - self._dst_saved)))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 260, in _naive_is_dst
    return time.localtime(timestamp + time.timezone).tm_isdst
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
2023-03-16 15:28:52 [DEBUG] botocore.utils utils.py:943: Unable to parse timestamp with "tzlocal" timezone info.
Traceback (most recent call last):
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\utils.py", line 941, in parse_timestamp
    return _parse_timestamp_with_tzinfo(value, tzinfo)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\utils.py", line 912, in _parse_timestamp_with_tzinfo
    return datetime.datetime.fromtimestamp(value, tzinfo())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 144, in fromutc
    return f(self, dt)
           ^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 258, in fromutc
    dt_wall = self._fromutc(dt)
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 222, in _fromutc
    dtoff = dt.utcoffset()
            ^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 222, in utcoffset
    if self._isdst(dt):
       ^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 294, in _isdst
    if self.is_ambiguous(dt):
       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 256, in is_ambiguous
    (naive_dst != self._naive_is_dst(dt - self._dst_saved)))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 260, in _naive_is_dst
    return time.localtime(timestamp + time.timezone).tm_isdst
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
2023-03-16 15:28:52 [DEBUG] botocore.hooks hooks.py:238: Event choose-signer.s3.GetObject: calling handler <bound method ClientCreator._default_s3_presign_to_sigv2 of <botocore.client.ClientCreator object at 0x00000270D1543FD0>>
2023-03-16 15:28:52 [DEBUG] botocore.hooks hooks.py:238: Event before-sign.s3.GetObject: calling handler <function remove_arn_from_signing_path at 0x00000270D1023240>
2023-03-16 15:28:52 [DEBUG] botocore.auth auth.py:830: Calculating signature using hmacv1 auth.
2023-03-16 15:28:52 [DEBUG] botocore.auth auth.py:832: HTTP request method: GET
2023-03-16 15:28:52 [DEBUG] botocore.auth auth.py:824: StringToSign:
GET


1678984132
/employees/dp/71c276d6-ab46-4edf-a12c-032ee0eebab3.jpg?response-expires=Thu, 01 Jan 1970 00:00:30 GMT
2023-03-16 15:31:59 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\apis\profile\update\profile_picture.py changed, reloading.
2023-03-16 15:32:00 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 15:35:18 [DEBUG] util.logger authenticate.py:55: employees authorization info : 5e69e7a3-1c05-4d70-a8f5-819c77dc3437 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 15:35:18 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 15:35:18 [DEBUG] botocore.hooks hooks.py:483: Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2023-03-16 15:35:18 [DEBUG] botocore.hooks hooks.py:483: Changing event name from before-call.apigateway to before-call.api-gateway
2023-03-16 15:35:18 [DEBUG] botocore.hooks hooks.py:483: Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2023-03-16 15:35:18 [DEBUG] botocore.hooks hooks.py:483: Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2023-03-16 15:35:18 [DEBUG] botocore.hooks hooks.py:483: Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2023-03-16 15:35:18 [DEBUG] botocore.hooks hooks.py:483: Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2023-03-16 15:35:18 [DEBUG] botocore.hooks hooks.py:483: Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2023-03-16 15:35:18 [DEBUG] botocore.hooks hooks.py:483: Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2023-03-16 15:35:18 [DEBUG] botocore.hooks hooks.py:483: Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2023-03-16 15:35:18 [DEBUG] botocore.hooks hooks.py:483: Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2023-03-16 15:35:18 [DEBUG] botocore.hooks hooks.py:483: Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2023-03-16 15:35:18 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\endpoints.json
2023-03-16 15:35:18 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\sdk-default-configuration.json
2023-03-16 15:35:18 [DEBUG] botocore.hooks hooks.py:238: Event choose-service-name: calling handler <function handle_service_name_alias at 0x0000013654EB74C0>
2023-03-16 15:35:18 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\s3\2006-03-01\service-2.json
2023-03-16 15:35:18 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\s3\2006-03-01\endpoint-rule-set-1.json.gz
2023-03-16 15:35:19 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\partitions.json
2023-03-16 15:35:19 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x0000013654E01800>
2023-03-16 15:35:19 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function lazy_call.<locals>._handler at 0x00000136553A5080>
2023-03-16 15:35:19 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x0000013654E01580>
2023-03-16 15:35:19 [DEBUG] botocore.endpoint endpoint.py:408: Setting s3 timeout as (60, 60)
2023-03-16 15:35:19 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\_retry.json
2023-03-16 15:35:19 [DEBUG] botocore.client client.py:278: Registering retry handlers for service: s3
2023-03-16 15:35:19 [DEBUG] botocore.utils utils.py:1522: Registering S3 region redirector handler
2023-03-16 15:35:19 [DEBUG] botocore.hooks hooks.py:238: Event before-endpoint-resolution.s3: calling handler <function customize_endpoint_resolver_builtins at 0x0000013654ED32E0>
2023-03-16 15:35:19 [DEBUG] botocore.hooks hooks.py:238: Event before-endpoint-resolution.s3: calling handler <bound method S3RegionRedirectorv2.redirect_from_cache of <botocore.utils.S3RegionRedirectorv2 object at 0x0000013656B496D0>>
2023-03-16 15:35:19 [DEBUG] botocore.regions regions.py:498: Calling endpoint provider with parameters: {'Bucket': 'employees', 'Region': 'us-east-1', 'UseFIPS': False, 'UseDualStack': False, 'Endpoint': 'https://s3.ap-southeast-1.wasabisys.com', 'ForcePathStyle': True, 'Accelerate': False, 'UseGlobalEndpoint': True, 'DisableMultiRegionAccessPoints': False, 'UseArnRegion': True}
2023-03-16 15:35:19 [DEBUG] botocore.regions regions.py:513: Endpoint provider result: https://s3.ap-southeast-1.wasabisys.com/employees
2023-03-16 15:35:19 [DEBUG] botocore.regions regions.py:660: Selecting from endpoint provider's list of auth schemes: "sigv4". User selected auth scheme is: "None"
2023-03-16 15:35:19 [DEBUG] botocore.regions regions.py:733: Selected auth type "v4" as "v4" with signing context params: {'region': 'us-east-1', 'signing_name': 's3', 'disableDoubleEncoding': True}
2023-03-16 15:35:19 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.GetObject: calling handler <function sse_md5 at 0x0000013654ED1080>
2023-03-16 15:35:19 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.GetObject: calling handler <function validate_bucket_name at 0x0000013654ED0FE0>
2023-03-16 15:35:19 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.GetObject: calling handler <function remove_bucket_from_url_paths_from_model at 0x0000013654ED3100>
2023-03-16 15:35:19 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.GetObject: calling handler <bound method S3RegionRedirectorv2.annotate_request_context of <botocore.utils.S3RegionRedirectorv2 object at 0x0000013656B496D0>>
2023-03-16 15:35:19 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.GetObject: calling handler <function generate_idempotent_uuid at 0x0000013654ED0E00>
2023-03-16 15:35:19 [DEBUG] botocore.utils utils.py:943: Unable to parse timestamp with "tzlocal" timezone info.
Traceback (most recent call last):
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\utils.py", line 941, in parse_timestamp
    return _parse_timestamp_with_tzinfo(value, tzinfo)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\utils.py", line 912, in _parse_timestamp_with_tzinfo
    return datetime.datetime.fromtimestamp(value, tzinfo())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 144, in fromutc
    return f(self, dt)
           ^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 258, in fromutc
    dt_wall = self._fromutc(dt)
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 222, in _fromutc
    dtoff = dt.utcoffset()
            ^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 222, in utcoffset
    if self._isdst(dt):
       ^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 294, in _isdst
    if self.is_ambiguous(dt):
       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 256, in is_ambiguous
    (naive_dst != self._naive_is_dst(dt - self._dst_saved)))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 260, in _naive_is_dst
    return time.localtime(timestamp + time.timezone).tm_isdst
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
2023-03-16 15:35:19 [DEBUG] botocore.utils utils.py:943: Unable to parse timestamp with "tzlocal" timezone info.
Traceback (most recent call last):
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\utils.py", line 941, in parse_timestamp
    return _parse_timestamp_with_tzinfo(value, tzinfo)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\utils.py", line 912, in _parse_timestamp_with_tzinfo
    return datetime.datetime.fromtimestamp(value, tzinfo())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 144, in fromutc
    return f(self, dt)
           ^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 258, in fromutc
    dt_wall = self._fromutc(dt)
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 222, in _fromutc
    dtoff = dt.utcoffset()
            ^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 222, in utcoffset
    if self._isdst(dt):
       ^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 294, in _isdst
    if self.is_ambiguous(dt):
       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 256, in is_ambiguous
    (naive_dst != self._naive_is_dst(dt - self._dst_saved)))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 260, in _naive_is_dst
    return time.localtime(timestamp + time.timezone).tm_isdst
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
2023-03-16 15:35:19 [DEBUG] botocore.hooks hooks.py:238: Event choose-signer.s3.GetObject: calling handler <bound method ClientCreator._default_s3_presign_to_sigv2 of <botocore.client.ClientCreator object at 0x0000013654F73F50>>
2023-03-16 15:35:19 [DEBUG] botocore.hooks hooks.py:238: Event before-sign.s3.GetObject: calling handler <function remove_arn_from_signing_path at 0x0000013654ED3240>
2023-03-16 15:35:19 [DEBUG] botocore.auth auth.py:830: Calculating signature using hmacv1 auth.
2023-03-16 15:35:19 [DEBUG] botocore.auth auth.py:832: HTTP request method: GET
2023-03-16 15:35:19 [DEBUG] botocore.auth auth.py:824: StringToSign:
GET


1678984519
/employees/id_proof/1111111-1111-4edf-a12c.jpg?response-expires=Thu, 01 Jan 1970 00:00:30 GMT
2023-03-16 15:35:19 [DEBUG] botocore.hooks hooks.py:238: Event choose-service-name: calling handler <function handle_service_name_alias at 0x0000013654EB74C0>
2023-03-16 15:35:19 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x0000013654E01800>
2023-03-16 15:35:19 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function lazy_call.<locals>._handler at 0x00000136553A5080>
2023-03-16 15:35:19 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x0000013654E01580>
2023-03-16 15:35:19 [DEBUG] botocore.endpoint endpoint.py:408: Setting s3 timeout as (60, 60)
2023-03-16 15:35:19 [DEBUG] botocore.client client.py:278: Registering retry handlers for service: s3
2023-03-16 15:35:19 [DEBUG] botocore.utils utils.py:1522: Registering S3 region redirector handler
2023-03-16 15:35:19 [DEBUG] botocore.hooks hooks.py:238: Event before-endpoint-resolution.s3: calling handler <function customize_endpoint_resolver_builtins at 0x0000013654ED32E0>
2023-03-16 15:35:19 [DEBUG] botocore.hooks hooks.py:238: Event before-endpoint-resolution.s3: calling handler <bound method S3RegionRedirectorv2.redirect_from_cache of <botocore.utils.S3RegionRedirectorv2 object at 0x0000013656D37B50>>
2023-03-16 15:35:19 [DEBUG] botocore.regions regions.py:498: Calling endpoint provider with parameters: {'Bucket': 'employees', 'Region': 'us-east-1', 'UseFIPS': False, 'UseDualStack': False, 'Endpoint': 'https://s3.ap-southeast-1.wasabisys.com', 'ForcePathStyle': True, 'Accelerate': False, 'UseGlobalEndpoint': True, 'DisableMultiRegionAccessPoints': False, 'UseArnRegion': True}
2023-03-16 15:35:19 [DEBUG] botocore.regions regions.py:513: Endpoint provider result: https://s3.ap-southeast-1.wasabisys.com/employees
2023-03-16 15:35:19 [DEBUG] botocore.regions regions.py:660: Selecting from endpoint provider's list of auth schemes: "sigv4". User selected auth scheme is: "None"
2023-03-16 15:35:19 [DEBUG] botocore.regions regions.py:733: Selected auth type "v4" as "v4" with signing context params: {'region': 'us-east-1', 'signing_name': 's3', 'disableDoubleEncoding': True}
2023-03-16 15:35:19 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.GetObject: calling handler <function sse_md5 at 0x0000013654ED1080>
2023-03-16 15:35:19 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.GetObject: calling handler <function validate_bucket_name at 0x0000013654ED0FE0>
2023-03-16 15:35:19 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.GetObject: calling handler <function remove_bucket_from_url_paths_from_model at 0x0000013654ED3100>
2023-03-16 15:35:19 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.GetObject: calling handler <bound method S3RegionRedirectorv2.annotate_request_context of <botocore.utils.S3RegionRedirectorv2 object at 0x0000013656D37B50>>
2023-03-16 15:35:19 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.GetObject: calling handler <function generate_idempotent_uuid at 0x0000013654ED0E00>
2023-03-16 15:35:19 [DEBUG] botocore.utils utils.py:943: Unable to parse timestamp with "tzlocal" timezone info.
Traceback (most recent call last):
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\utils.py", line 941, in parse_timestamp
    return _parse_timestamp_with_tzinfo(value, tzinfo)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\utils.py", line 912, in _parse_timestamp_with_tzinfo
    return datetime.datetime.fromtimestamp(value, tzinfo())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 144, in fromutc
    return f(self, dt)
           ^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 258, in fromutc
    dt_wall = self._fromutc(dt)
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 222, in _fromutc
    dtoff = dt.utcoffset()
            ^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 222, in utcoffset
    if self._isdst(dt):
       ^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 294, in _isdst
    if self.is_ambiguous(dt):
       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 256, in is_ambiguous
    (naive_dst != self._naive_is_dst(dt - self._dst_saved)))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 260, in _naive_is_dst
    return time.localtime(timestamp + time.timezone).tm_isdst
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
2023-03-16 15:35:19 [DEBUG] botocore.utils utils.py:943: Unable to parse timestamp with "tzlocal" timezone info.
Traceback (most recent call last):
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\utils.py", line 941, in parse_timestamp
    return _parse_timestamp_with_tzinfo(value, tzinfo)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\utils.py", line 912, in _parse_timestamp_with_tzinfo
    return datetime.datetime.fromtimestamp(value, tzinfo())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 144, in fromutc
    return f(self, dt)
           ^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 258, in fromutc
    dt_wall = self._fromutc(dt)
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 222, in _fromutc
    dtoff = dt.utcoffset()
            ^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 222, in utcoffset
    if self._isdst(dt):
       ^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 294, in _isdst
    if self.is_ambiguous(dt):
       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 256, in is_ambiguous
    (naive_dst != self._naive_is_dst(dt - self._dst_saved)))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 260, in _naive_is_dst
    return time.localtime(timestamp + time.timezone).tm_isdst
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
2023-03-16 15:35:19 [DEBUG] botocore.hooks hooks.py:238: Event choose-signer.s3.GetObject: calling handler <bound method ClientCreator._default_s3_presign_to_sigv2 of <botocore.client.ClientCreator object at 0x000001365494D090>>
2023-03-16 15:35:19 [DEBUG] botocore.hooks hooks.py:238: Event before-sign.s3.GetObject: calling handler <function remove_arn_from_signing_path at 0x0000013654ED3240>
2023-03-16 15:35:19 [DEBUG] botocore.auth auth.py:830: Calculating signature using hmacv1 auth.
2023-03-16 15:35:19 [DEBUG] botocore.auth auth.py:832: HTTP request method: GET
2023-03-16 15:35:19 [DEBUG] botocore.auth auth.py:824: StringToSign:
GET


1678984519
/employees/id_proof/22222222-2222-4edf-a12c.jpg?response-expires=Thu, 01 Jan 1970 00:00:30 GMT
2023-03-16 15:36:28 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\apis\profile\update\id_proof.py changed, reloading.
2023-03-16 15:36:28 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 15:37:45 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\apis\profile\update\id_proof.py changed, reloading.
2023-03-16 15:37:46 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 15:38:07 [DEBUG] util.logger authenticate.py:55: employees authorization info : 5e69e7a3-1c05-4d70-a8f5-819c77dc3437 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 15:38:07 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 15:38:07 [ERROR] util.logger id_proof.py:42: Failed to update ID Proof for employee c577aff1-b951-404d-84a9-8739a4c43917 - ID Proof cannot be empty
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\profile\update\id_proof.py", line 20, in index
    raise Exception("ID Proof cannot be empty")
Exception: ID Proof cannot be empty

2023-03-16 15:38:07 [WARNING] django.request log.py:241: Bad Request: /employees/apis/profile/update/idproof/
2023-03-16 15:38:14 [DEBUG] util.logger authenticate.py:55: employees authorization info : 5e69e7a3-1c05-4d70-a8f5-819c77dc3437 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 15:38:14 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 15:38:14 [ERROR] util.logger id_proof.py:42: Failed to update ID Proof for employee c577aff1-b951-404d-84a9-8739a4c43917 - Invalid Document Type
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\profile\update\id_proof.py", line 16, in index
    document_type = __validate_and_format_document_type(data.get("document_type", None))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\aravind\lens35\apps\employees\apis\profile\update\id_proof.py", line 61, in __validate_and_format_document_type
    raise Exception("Invalid Document Type")
Exception: Invalid Document Type

2023-03-16 15:38:14 [WARNING] django.request log.py:241: Bad Request: /employees/apis/profile/update/idproof/
2023-03-16 15:39:09 [DEBUG] util.logger authenticate.py:55: employees authorization info : 5e69e7a3-1c05-4d70-a8f5-819c77dc3437 | Identifier : c577aff1-b951-404d-84a9-8739a4c43917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-16 15:39:09 [DEBUG] util.logger authenticate.py:68: KeepActive is true for this Token.
2023-03-16 15:39:09 [DEBUG] botocore.hooks hooks.py:483: Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2023-03-16 15:39:09 [DEBUG] botocore.hooks hooks.py:483: Changing event name from before-call.apigateway to before-call.api-gateway
2023-03-16 15:39:09 [DEBUG] botocore.hooks hooks.py:483: Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2023-03-16 15:39:09 [DEBUG] botocore.hooks hooks.py:483: Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2023-03-16 15:39:09 [DEBUG] botocore.hooks hooks.py:483: Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2023-03-16 15:39:09 [DEBUG] botocore.hooks hooks.py:483: Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2023-03-16 15:39:09 [DEBUG] botocore.hooks hooks.py:483: Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2023-03-16 15:39:09 [DEBUG] botocore.hooks hooks.py:483: Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2023-03-16 15:39:09 [DEBUG] botocore.hooks hooks.py:483: Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2023-03-16 15:39:09 [DEBUG] botocore.hooks hooks.py:483: Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2023-03-16 15:39:09 [DEBUG] botocore.hooks hooks.py:483: Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2023-03-16 15:39:09 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\endpoints.json
2023-03-16 15:39:09 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\sdk-default-configuration.json
2023-03-16 15:39:09 [DEBUG] botocore.hooks hooks.py:238: Event choose-service-name: calling handler <function handle_service_name_alias at 0x0000024F67A374C0>
2023-03-16 15:39:09 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\s3\2006-03-01\service-2.json
2023-03-16 15:39:09 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\s3\2006-03-01\endpoint-rule-set-1.json.gz
2023-03-16 15:39:09 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\partitions.json
2023-03-16 15:39:09 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x0000024F67985800>
2023-03-16 15:39:09 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function lazy_call.<locals>._handler at 0x0000024F67CFFCE0>
2023-03-16 15:39:09 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x0000024F67985580>
2023-03-16 15:39:09 [DEBUG] botocore.endpoint endpoint.py:408: Setting s3 timeout as (60, 60)
2023-03-16 15:39:10 [DEBUG] botocore.loaders loaders.py:180: Loading JSON file: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\data\_retry.json
2023-03-16 15:39:10 [DEBUG] botocore.client client.py:278: Registering retry handlers for service: s3
2023-03-16 15:39:10 [DEBUG] botocore.utils utils.py:1522: Registering S3 region redirector handler
2023-03-16 15:39:10 [DEBUG] botocore.hooks hooks.py:238: Event before-endpoint-resolution.s3: calling handler <function customize_endpoint_resolver_builtins at 0x0000024F67A532E0>
2023-03-16 15:39:10 [DEBUG] botocore.hooks hooks.py:238: Event before-endpoint-resolution.s3: calling handler <bound method S3RegionRedirectorv2.redirect_from_cache of <botocore.utils.S3RegionRedirectorv2 object at 0x0000024F69747790>>
2023-03-16 15:39:10 [DEBUG] botocore.regions regions.py:498: Calling endpoint provider with parameters: {'Bucket': 'employees', 'Region': 'us-east-1', 'UseFIPS': False, 'UseDualStack': False, 'Endpoint': 'https://s3.ap-southeast-1.wasabisys.com', 'ForcePathStyle': True, 'Accelerate': False, 'UseGlobalEndpoint': True, 'DisableMultiRegionAccessPoints': False, 'UseArnRegion': True}
2023-03-16 15:39:10 [DEBUG] botocore.regions regions.py:513: Endpoint provider result: https://s3.ap-southeast-1.wasabisys.com/employees
2023-03-16 15:39:10 [DEBUG] botocore.regions regions.py:660: Selecting from endpoint provider's list of auth schemes: "sigv4". User selected auth scheme is: "None"
2023-03-16 15:39:10 [DEBUG] botocore.regions regions.py:733: Selected auth type "v4" as "v4" with signing context params: {'region': 'us-east-1', 'signing_name': 's3', 'disableDoubleEncoding': True}
2023-03-16 15:39:10 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.DeleteObject: calling handler <function validate_bucket_name at 0x0000024F67A50FE0>
2023-03-16 15:39:10 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.DeleteObject: calling handler <function remove_bucket_from_url_paths_from_model at 0x0000024F67A53100>
2023-03-16 15:39:10 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.DeleteObject: calling handler <bound method S3RegionRedirectorv2.annotate_request_context of <botocore.utils.S3RegionRedirectorv2 object at 0x0000024F69747790>>
2023-03-16 15:39:10 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.DeleteObject: calling handler <function generate_idempotent_uuid at 0x0000024F67A50E00>
2023-03-16 15:39:10 [DEBUG] botocore.hooks hooks.py:238: Event before-call.s3.DeleteObject: calling handler <function add_expect_header at 0x0000024F67A513A0>
2023-03-16 15:39:10 [DEBUG] botocore.hooks hooks.py:238: Event before-call.s3.DeleteObject: calling handler <function add_recursion_detection_header at 0x0000024F67A37600>
2023-03-16 15:39:10 [DEBUG] botocore.hooks hooks.py:238: Event before-call.s3.DeleteObject: calling handler <function inject_api_version_header_if_needed at 0x0000024F67A528E0>
2023-03-16 15:39:10 [DEBUG] botocore.endpoint endpoint.py:114: Making request for OperationModel(name=DeleteObject) with params: {'url_path': '/id_proof/1111111-1111-4edf-a12c.jpg', 'query_string': {}, 'method': 'DELETE', 'headers': {'User-Agent': 'Boto3/1.26.92 Python/3.11.1 Windows/10 Botocore/1.29.92'}, 'body': b'', 'auth_path': '/employees/id_proof/1111111-1111-4edf-a12c.jpg', 'url': 'https://s3.ap-southeast-1.wasabisys.com/employees/id_proof/1111111-1111-4edf-a12c.jpg', 'context': {'client_region': 'us-east-1', 'client_config': <botocore.config.Config object at 0x0000024F698B19D0>, 'has_streaming_input': False, 'auth_type': 'v4', 'signing': {'region': 'us-east-1', 'signing_name': 's3', 'disableDoubleEncoding': True}, 's3_redirect': {'redirected': False, 'bucket': 'employees', 'params': {'Bucket': 'employees', 'Key': 'id_proof/1111111-1111-4edf-a12c.jpg'}}}}
2023-03-16 15:39:10 [DEBUG] botocore.hooks hooks.py:238: Event request-created.s3.DeleteObject: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x0000024F6972CE10>>
2023-03-16 15:39:10 [DEBUG] botocore.hooks hooks.py:238: Event choose-signer.s3.DeleteObject: calling handler <bound method ClientCreator._default_s3_presign_to_sigv2 of <botocore.client.ClientCreator object at 0x0000024F66490190>>
2023-03-16 15:39:10 [DEBUG] botocore.hooks hooks.py:238: Event choose-signer.s3.DeleteObject: calling handler <function set_operation_specific_signer at 0x0000024F67A50CC0>
2023-03-16 15:39:10 [DEBUG] botocore.hooks hooks.py:238: Event before-sign.s3.DeleteObject: calling handler <function remove_arn_from_signing_path at 0x0000024F67A53240>
2023-03-16 15:39:10 [DEBUG] botocore.auth auth.py:425: Calculating signature using v4 auth.
2023-03-16 15:39:10 [DEBUG] botocore.auth auth.py:426: CanonicalRequest:
DELETE
/employees/id_proof/1111111-1111-4edf-a12c.jpg

host:s3.ap-southeast-1.wasabisys.com
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20230316T153910Z

host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2023-03-16 15:39:10 [DEBUG] botocore.auth auth.py:428: StringToSign:
AWS4-HMAC-SHA256
20230316T153910Z
20230316/us-east-1/s3/aws4_request
68554306dc1223be4f6472aadbc9aba76682f443e21a9dba7797d10babc21899
2023-03-16 15:39:10 [DEBUG] botocore.auth auth.py:430: Signature:
15bafbf60f050b22cc02db91a73597a8dedf274e2f0819da1857e3b744766dfd
2023-03-16 15:39:10 [DEBUG] botocore.hooks hooks.py:238: Event request-created.s3.DeleteObject: calling handler <function add_retry_headers at 0x0000024F67A53060>
2023-03-16 15:39:10 [DEBUG] botocore.endpoint endpoint.py:265: Sending http request: <AWSPreparedRequest stream_output=False, method=DELETE, url=https://s3.ap-southeast-1.wasabisys.com/employees/id_proof/1111111-1111-4edf-a12c.jpg, headers={'User-Agent': b'Boto3/1.26.92 Python/3.11.1 Windows/10 Botocore/1.29.92', 'X-Amz-Date': b'20230316T153910Z', 'X-Amz-Content-SHA256': b'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'Authorization': b'AWS4-HMAC-SHA256 Credential=C3DQUWUT8FKRKY0IKQ88/20230316/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=15bafbf60f050b22cc02db91a73597a8dedf274e2f0819da1857e3b744766dfd', 'amz-sdk-invocation-id': b'4cf593f6-c12d-4472-97ba-14b836ed4825', 'amz-sdk-request': b'attempt=1', 'Content-Length': '0'}>
2023-03-16 15:39:10 [DEBUG] botocore.httpsession httpsession.py:90: Certificate path: C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\cacert.pem
2023-03-16 15:39:10 [DEBUG] urllib3.connectionpool connectionpool.py:1003: Starting new HTTPS connection (1): s3.ap-southeast-1.wasabisys.com:443
2023-03-16 15:39:11 [DEBUG] urllib3.connectionpool connectionpool.py:456: https://s3.ap-southeast-1.wasabisys.com:443 "DELETE /employees/id_proof/1111111-1111-4edf-a12c.jpg HTTP/1.1" 403 None
2023-03-16 15:39:11 [DEBUG] botocore.parsers parsers.py:240: Response headers: {'Content-Type': 'application/xml', 'Date': 'Thu, 16 Mar 2023 15:39:11 GMT', 'Server': 'WasabiS3/7.12.1004-2023-02-17-7ff2f5bdd9 (head4)', 'x-amz-id-2': '8sIA0zMIt4U6U9e7XIcxmS6QGU259Jswvdg7Ep3xs1aT6m8gjR8MqKTtXHSFWH/ISdCozPO22V8D', 'x-amz-request-id': '43E14BDB74084DD2', 'Transfer-Encoding': 'chunked'}
2023-03-16 15:39:11 [DEBUG] botocore.parsers parsers.py:241: Response body:
b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>PoorAccountStanding</Code><Message>Could not perform operation because of poor account standing or trial period expiry. Please have your Wasabi account administrator update billing information for the account.</Message><OwnerAccountCanonicalId>C1AE454B95E45DE92E1E96976FF1A0E2EFB08EB789D5C697810475735DDE5987</OwnerAccountCanonicalId><RequestId>43E14BDB74084DD2</RequestId><HostId>8sIA0zMIt4U6U9e7XIcxmS6QGU259Jswvdg7Ep3xs1aT6m8gjR8MqKTtXHSFWH/ISdCozPO22V8D</HostId></Error>'
2023-03-16 15:39:11 [DEBUG] botocore.hooks hooks.py:238: Event needs-retry.s3.DeleteObject: calling handler <botocore.retryhandler.RetryHandler object at 0x0000024F69750210>
2023-03-16 15:39:11 [DEBUG] botocore.retryhandler retryhandler.py:211: No retry needed.
2023-03-16 15:39:11 [DEBUG] botocore.hooks hooks.py:238: Event needs-retry.s3.DeleteObject: calling handler <bound method S3RegionRedirectorv2.redirect_from_error of <botocore.utils.S3RegionRedirectorv2 object at 0x0000024F69747790>>
2023-03-16 15:39:11 [ERROR] util.logger id_proof.py:29: Failed to delete the old ID Proof of employee c577aff1-b951-404d-84a9-8739a4c43917 - An error occurred (PoorAccountStanding) when calling the DeleteObject operation: Could not perform operation because of poor account standing or trial period expiry. Please have your Wasabi account administrator update billing information for the account.
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\profile\update\id_proof.py", line 24, in index
    delete_file_from_bucket(EMPLOYEES_BUCKET, EMPLOYEES_ID_PROOF_FOLDER, employee.id_proof_front)
  File "C:\aravind\lens35\util\wasabi.py", line 40, in delete_file_from_bucket
    s3.delete_object(Bucket=bucket_name, Key=key)
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (PoorAccountStanding) when calling the DeleteObject operation: Could not perform operation because of poor account standing or trial period expiry. Please have your Wasabi account administrator update billing information for the account.

2023-03-16 15:39:11 [DEBUG] botocore.hooks hooks.py:238: Event choose-service-name: calling handler <function handle_service_name_alias at 0x0000024F67A374C0>
2023-03-16 15:39:11 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x0000024F67985800>
2023-03-16 15:39:11 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function lazy_call.<locals>._handler at 0x0000024F67CFFCE0>
2023-03-16 15:39:11 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x0000024F67985580>
2023-03-16 15:39:11 [DEBUG] botocore.endpoint endpoint.py:408: Setting s3 timeout as (60, 60)
2023-03-16 15:39:11 [DEBUG] botocore.client client.py:278: Registering retry handlers for service: s3
2023-03-16 15:39:11 [DEBUG] botocore.utils utils.py:1522: Registering S3 region redirector handler
2023-03-16 15:39:11 [DEBUG] botocore.hooks hooks.py:238: Event before-endpoint-resolution.s3: calling handler <function customize_endpoint_resolver_builtins at 0x0000024F67A532E0>
2023-03-16 15:39:11 [DEBUG] botocore.hooks hooks.py:238: Event before-endpoint-resolution.s3: calling handler <bound method S3RegionRedirectorv2.redirect_from_cache of <botocore.utils.S3RegionRedirectorv2 object at 0x0000024F67F88050>>
2023-03-16 15:39:11 [DEBUG] botocore.regions regions.py:498: Calling endpoint provider with parameters: {'Bucket': 'employees', 'Region': 'us-east-1', 'UseFIPS': False, 'UseDualStack': False, 'Endpoint': 'https://s3.ap-southeast-1.wasabisys.com', 'ForcePathStyle': True, 'Accelerate': False, 'UseGlobalEndpoint': True, 'DisableMultiRegionAccessPoints': False, 'UseArnRegion': True}
2023-03-16 15:39:11 [DEBUG] botocore.regions regions.py:513: Endpoint provider result: https://s3.ap-southeast-1.wasabisys.com/employees
2023-03-16 15:39:11 [DEBUG] botocore.regions regions.py:660: Selecting from endpoint provider's list of auth schemes: "sigv4". User selected auth scheme is: "None"
2023-03-16 15:39:11 [DEBUG] botocore.regions regions.py:733: Selected auth type "v4" as "v4" with signing context params: {'region': 'us-east-1', 'signing_name': 's3', 'disableDoubleEncoding': True}
2023-03-16 15:39:11 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.GetObject: calling handler <function sse_md5 at 0x0000024F67A51080>
2023-03-16 15:39:11 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.GetObject: calling handler <function validate_bucket_name at 0x0000024F67A50FE0>
2023-03-16 15:39:11 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.GetObject: calling handler <function remove_bucket_from_url_paths_from_model at 0x0000024F67A53100>
2023-03-16 15:39:11 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.GetObject: calling handler <bound method S3RegionRedirectorv2.annotate_request_context of <botocore.utils.S3RegionRedirectorv2 object at 0x0000024F67F88050>>
2023-03-16 15:39:11 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.GetObject: calling handler <function generate_idempotent_uuid at 0x0000024F67A50E00>
2023-03-16 15:39:11 [DEBUG] botocore.utils utils.py:943: Unable to parse timestamp with "tzlocal" timezone info.
Traceback (most recent call last):
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\utils.py", line 941, in parse_timestamp
    return _parse_timestamp_with_tzinfo(value, tzinfo)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\utils.py", line 912, in _parse_timestamp_with_tzinfo
    return datetime.datetime.fromtimestamp(value, tzinfo())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 144, in fromutc
    return f(self, dt)
           ^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 258, in fromutc
    dt_wall = self._fromutc(dt)
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 222, in _fromutc
    dtoff = dt.utcoffset()
            ^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 222, in utcoffset
    if self._isdst(dt):
       ^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 294, in _isdst
    if self.is_ambiguous(dt):
       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 256, in is_ambiguous
    (naive_dst != self._naive_is_dst(dt - self._dst_saved)))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 260, in _naive_is_dst
    return time.localtime(timestamp + time.timezone).tm_isdst
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
2023-03-16 15:39:11 [DEBUG] botocore.utils utils.py:943: Unable to parse timestamp with "tzlocal" timezone info.
Traceback (most recent call last):
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\utils.py", line 941, in parse_timestamp
    return _parse_timestamp_with_tzinfo(value, tzinfo)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\utils.py", line 912, in _parse_timestamp_with_tzinfo
    return datetime.datetime.fromtimestamp(value, tzinfo())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 144, in fromutc
    return f(self, dt)
           ^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 258, in fromutc
    dt_wall = self._fromutc(dt)
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 222, in _fromutc
    dtoff = dt.utcoffset()
            ^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 222, in utcoffset
    if self._isdst(dt):
       ^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 294, in _isdst
    if self.is_ambiguous(dt):
       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 256, in is_ambiguous
    (naive_dst != self._naive_is_dst(dt - self._dst_saved)))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 260, in _naive_is_dst
    return time.localtime(timestamp + time.timezone).tm_isdst
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
2023-03-16 15:39:11 [DEBUG] botocore.hooks hooks.py:238: Event choose-signer.s3.GetObject: calling handler <bound method ClientCreator._default_s3_presign_to_sigv2 of <botocore.client.ClientCreator object at 0x0000024F6973C810>>
2023-03-16 15:39:11 [DEBUG] botocore.hooks hooks.py:238: Event before-sign.s3.GetObject: calling handler <function remove_arn_from_signing_path at 0x0000024F67A53240>
2023-03-16 15:39:11 [DEBUG] botocore.auth auth.py:830: Calculating signature using hmacv1 auth.
2023-03-16 15:39:11 [DEBUG] botocore.auth auth.py:832: HTTP request method: GET
2023-03-16 15:39:11 [DEBUG] botocore.auth auth.py:824: StringToSign:
GET


1678984751
/employees/id_proof/1111111-1111-4edf-a12c.jpg?response-expires=Thu, 01 Jan 1970 00:00:30 GMT
2023-03-16 15:39:11 [DEBUG] botocore.hooks hooks.py:238: Event choose-service-name: calling handler <function handle_service_name_alias at 0x0000024F67A374C0>
2023-03-16 15:39:11 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x0000024F67985800>
2023-03-16 15:39:11 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function lazy_call.<locals>._handler at 0x0000024F67CFFCE0>
2023-03-16 15:39:11 [DEBUG] botocore.hooks hooks.py:238: Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x0000024F67985580>
2023-03-16 15:39:11 [DEBUG] botocore.endpoint endpoint.py:408: Setting s3 timeout as (60, 60)
2023-03-16 15:39:11 [DEBUG] botocore.client client.py:278: Registering retry handlers for service: s3
2023-03-16 15:39:11 [DEBUG] botocore.utils utils.py:1522: Registering S3 region redirector handler
2023-03-16 15:39:11 [DEBUG] botocore.hooks hooks.py:238: Event before-endpoint-resolution.s3: calling handler <function customize_endpoint_resolver_builtins at 0x0000024F67A532E0>
2023-03-16 15:39:11 [DEBUG] botocore.hooks hooks.py:238: Event before-endpoint-resolution.s3: calling handler <bound method S3RegionRedirectorv2.redirect_from_cache of <botocore.utils.S3RegionRedirectorv2 object at 0x0000024F68058810>>
2023-03-16 15:39:11 [DEBUG] botocore.regions regions.py:498: Calling endpoint provider with parameters: {'Bucket': 'employees', 'Region': 'us-east-1', 'UseFIPS': False, 'UseDualStack': False, 'Endpoint': 'https://s3.ap-southeast-1.wasabisys.com', 'ForcePathStyle': True, 'Accelerate': False, 'UseGlobalEndpoint': True, 'DisableMultiRegionAccessPoints': False, 'UseArnRegion': True}
2023-03-16 15:39:11 [DEBUG] botocore.regions regions.py:513: Endpoint provider result: https://s3.ap-southeast-1.wasabisys.com/employees
2023-03-16 15:39:11 [DEBUG] botocore.regions regions.py:660: Selecting from endpoint provider's list of auth schemes: "sigv4". User selected auth scheme is: "None"
2023-03-16 15:39:11 [DEBUG] botocore.regions regions.py:733: Selected auth type "v4" as "v4" with signing context params: {'region': 'us-east-1', 'signing_name': 's3', 'disableDoubleEncoding': True}
2023-03-16 15:39:11 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.GetObject: calling handler <function sse_md5 at 0x0000024F67A51080>
2023-03-16 15:39:11 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.GetObject: calling handler <function validate_bucket_name at 0x0000024F67A50FE0>
2023-03-16 15:39:11 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.GetObject: calling handler <function remove_bucket_from_url_paths_from_model at 0x0000024F67A53100>
2023-03-16 15:39:11 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.GetObject: calling handler <bound method S3RegionRedirectorv2.annotate_request_context of <botocore.utils.S3RegionRedirectorv2 object at 0x0000024F68058810>>
2023-03-16 15:39:11 [DEBUG] botocore.hooks hooks.py:238: Event before-parameter-build.s3.GetObject: calling handler <function generate_idempotent_uuid at 0x0000024F67A50E00>
2023-03-16 15:39:11 [DEBUG] botocore.utils utils.py:943: Unable to parse timestamp with "tzlocal" timezone info.
Traceback (most recent call last):
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\utils.py", line 941, in parse_timestamp
    return _parse_timestamp_with_tzinfo(value, tzinfo)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\utils.py", line 912, in _parse_timestamp_with_tzinfo
    return datetime.datetime.fromtimestamp(value, tzinfo())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 144, in fromutc
    return f(self, dt)
           ^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 258, in fromutc
    dt_wall = self._fromutc(dt)
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 222, in _fromutc
    dtoff = dt.utcoffset()
            ^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 222, in utcoffset
    if self._isdst(dt):
       ^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 294, in _isdst
    if self.is_ambiguous(dt):
       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 256, in is_ambiguous
    (naive_dst != self._naive_is_dst(dt - self._dst_saved)))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 260, in _naive_is_dst
    return time.localtime(timestamp + time.timezone).tm_isdst
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
2023-03-16 15:39:11 [DEBUG] botocore.utils utils.py:943: Unable to parse timestamp with "tzlocal" timezone info.
Traceback (most recent call last):
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\utils.py", line 941, in parse_timestamp
    return _parse_timestamp_with_tzinfo(value, tzinfo)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\botocore\utils.py", line 912, in _parse_timestamp_with_tzinfo
    return datetime.datetime.fromtimestamp(value, tzinfo())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 144, in fromutc
    return f(self, dt)
           ^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 258, in fromutc
    dt_wall = self._fromutc(dt)
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\_common.py", line 222, in _fromutc
    dtoff = dt.utcoffset()
            ^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 222, in utcoffset
    if self._isdst(dt):
       ^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 294, in _isdst
    if self.is_ambiguous(dt):
       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 256, in is_ambiguous
    (naive_dst != self._naive_is_dst(dt - self._dst_saved)))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\dateutil\tz\tz.py", line 260, in _naive_is_dst
    return time.localtime(timestamp + time.timezone).tm_isdst
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
2023-03-16 15:39:11 [DEBUG] botocore.hooks hooks.py:238: Event choose-signer.s3.GetObject: calling handler <bound method ClientCreator._default_s3_presign_to_sigv2 of <botocore.client.ClientCreator object at 0x0000024F68094090>>
2023-03-16 15:39:11 [DEBUG] botocore.hooks hooks.py:238: Event before-sign.s3.GetObject: calling handler <function remove_arn_from_signing_path at 0x0000024F67A53240>
2023-03-16 15:39:11 [DEBUG] botocore.auth auth.py:830: Calculating signature using hmacv1 auth.
2023-03-16 15:39:11 [DEBUG] botocore.auth auth.py:832: HTTP request method: GET
2023-03-16 15:39:11 [DEBUG] botocore.auth auth.py:824: StringToSign:
GET


1678984751
/employees/id_proof/22222222-2222-4edf-a12c.jpg?response-expires=Thu, 01 Jan 1970 00:00:30 GMT
2023-03-16 15:40:02 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\api_urls.py changed, reloading.
2023-03-16 15:40:02 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-16 16:05:29 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\lens35\constanst.py changed, reloading.
2023-03-16 16:05:30 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
